/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param displayName 
 * @param description 
 * @param priceNaira 
 * @param pricingModel 
 * @param active 
 */
@Serializable

data class AddOn (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "price_naira")
    val priceNaira: kotlin.Int,

    @SerialName(value = "pricing_model")
    val pricingModel: kotlin.String,

    @SerialName(value = "active")
    val active: kotlin.Boolean

) {


}

