/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param memberEmail 
 * @param role 
 */
@Serializable

data class AddSharedMemberRequest (

    @SerialName(value = "member_email")
    val memberEmail: kotlin.String,

    @SerialName(value = "role")
    val role: AddSharedMemberRequest.Role? = Role.member

) {

    /**
     * 
     *
     * Values: manager,member
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "manager") manager("manager"),
        @SerialName(value = "member") member("member");
    }

}

