/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param eventType 
 * @param detail 
 * @param ip 
 * @param time 
 */
@Serializable

data class AuditEvent (

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "event_type")
    val eventType: kotlin.String? = null,

    @SerialName(value = "detail")
    val detail: kotlin.String? = null,

    @SerialName(value = "ip")
    val ip: kotlin.String? = null,

    @Contextual @SerialName(value = "time")
    val time: kotlin.time.Instant? = null

) {


}

