/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param index 
 * @param id 
 * @param messageId 
 * @param status 
 * @param error Present when this message failed; the others are then absent.
 */
@Serializable

data class BatchResult (

    @SerialName(value = "index")
    val index: kotlin.Int? = null,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "message_id")
    val messageId: kotlin.String? = null,

    @SerialName(value = "status")
    val status: BatchResult.Status? = null,

    /* Present when this message failed; the others are then absent. */
    @SerialName(value = "error")
    val error: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: queued,scheduled,suppressed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "queued") queued("queued"),
        @SerialName(value = "scheduled") scheduled("scheduled"),
        @SerialName(value = "suppressed") suppressed("suppressed");
    }

}

