/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param name 
 * @param visibility 
 * @param createdAt 
 * @param updatedAt 
 * @param color 
 * @param ownerEmail 
 * @param description 
 * @param feedUrl 
 * @param eventCount 
 */
@Serializable

data class Calendar (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "tenant_id")
    val tenantId: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "visibility")
    val visibility: Calendar.Visibility,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.time.Instant,

    @SerialName(value = "color")
    val color: kotlin.String? = null,

    @SerialName(value = "owner_email")
    val ownerEmail: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @Contextual @SerialName(value = "feed_url")
    val feedUrl: java.net.URI? = null,

    @SerialName(value = "event_count")
    val eventCount: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: `private`,tenant
     */
    @Serializable
    enum class Visibility(val value: kotlin.String) {
        @SerialName(value = "private") `private`("private"),
        @SerialName(value = "tenant") tenant("tenant");
    }

}

