/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param name 
 * @param visibility 
 * @param memberCount 
 * @param createdAt 
 * @param updatedAt 
 * @param description 
 */
@Serializable

data class ContactList (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "tenant_id")
    val tenantId: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "visibility")
    val visibility: ContactList.Visibility,

    @SerialName(value = "member_count")
    val memberCount: kotlin.Int,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.time.Instant,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: company_wide,restricted
     */
    @Serializable
    enum class Visibility(val value: kotlin.String) {
        @SerialName(value = "company_wide") company_wide("company_wide"),
        @SerialName(value = "restricted") restricted("restricted");
    }

}

