/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param provider 
 * @param label 
 */
@Serializable

data class CreateCalendarIntegrationRequest (

    @SerialName(value = "provider")
    val provider: CreateCalendarIntegrationRequest.Provider,

    @SerialName(value = "label")
    val label: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: exchange,google_calendar,teams,zoom,erp
     */
    @Serializable
    enum class Provider(val value: kotlin.String) {
        @SerialName(value = "exchange") exchange("exchange"),
        @SerialName(value = "google_calendar") google_calendar("google_calendar"),
        @SerialName(value = "teams") teams("teams"),
        @SerialName(value = "zoom") zoom("zoom"),
        @SerialName(value = "erp") erp("erp");
    }

}

