/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authorizationUrl 
 * @param reference 
 * @param units 
 */
@Serializable

data class CreateUnitsCheckout200Response (

    @Contextual @SerialName(value = "authorization_url")
    val authorizationUrl: java.net.URI,

    @SerialName(value = "reference")
    val reference: kotlin.String,

    @SerialName(value = "units")
    val units: kotlin.Int

) {


}

