/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param listAddress 
 * @param name 
 * @param members 
 */
@Serializable

data class CreateDistributionListRequest (

    @SerialName(value = "list_address")
    val listAddress: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "members")
    val members: kotlin.collections.List<kotlin.String>? = null

) {


}

