/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param description 
 * @param visibility 
 */
@Serializable

data class CreateContactListRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "visibility")
    val visibility: CreateContactListRequest.Visibility? = Visibility.company_wide

) {

    /**
     * 
     *
     * Values: company_wide,restricted
     */
    @Serializable
    enum class Visibility(val value: kotlin.String) {
        @SerialName(value = "company_wide") company_wide("company_wide"),
        @SerialName(value = "restricted") restricted("restricted");
    }

}

