/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param bundle 
 */
@Serializable

data class CreateUnitsCheckoutRequest (

    @SerialName(value = "bundle")
    val bundle: CreateUnitsCheckoutRequest.Bundle

) {

    /**
     * 
     *
     * Values: _1k,_10k,_50k,_100k,_1pkt,_5pkt,_10pkt,_20pkt
     */
    @Serializable
    enum class Bundle(val value: kotlin.String) {
        @SerialName(value = "1k") _1k("1k"),
        @SerialName(value = "10k") _10k("10k"),
        @SerialName(value = "50k") _50k("50k"),
        @SerialName(value = "100k") _100k("100k"),
        @SerialName(value = "1pkt") _1pkt("1pkt"),
        @SerialName(value = "5pkt") _5pkt("5pkt"),
        @SerialName(value = "10pkt") _10pkt("10pkt"),
        @SerialName(value = "20pkt") _20pkt("20pkt");
    }

}

