/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param name 
 * @param `value` 
 * @param ttl 
 * @param purpose 
 * @param priority MX records only.
 */
@Serializable

data class DNSRecord (

    @SerialName(value = "type")
    val type: DNSRecord.Type,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "value")
    val `value`: kotlin.String,

    @SerialName(value = "ttl")
    val ttl: kotlin.Int,

    @SerialName(value = "purpose")
    val purpose: DNSRecord.Purpose,

    /* MX records only. */
    @SerialName(value = "priority")
    val priority: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: TXT,MX
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "TXT") TXT("TXT"),
        @SerialName(value = "MX") MX("MX");
    }
    /**
     * 
     *
     * Values: verification,spf,dkim,mxMinusPrimary,mxMinusBackup,dmarc
     */
    @Serializable
    enum class Purpose(val value: kotlin.String) {
        @SerialName(value = "verification") verification("verification"),
        @SerialName(value = "spf") spf("spf"),
        @SerialName(value = "dkim") dkim("dkim"),
        @SerialName(value = "mx-primary") mxMinusPrimary("mx-primary"),
        @SerialName(value = "mx-backup") mxMinusBackup("mx-backup"),
        @SerialName(value = "dmarc") dmarc("dmarc");
    }

}

