/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import com.lockally.sdk.model.ContactList
import com.lockally.sdk.model.GetContactList200ResponseMembersInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param list 
 * @param members 
 */
@Serializable

data class GetContactList200Response (

    @SerialName(value = "list")
    val list: ContactList? = null,

    @SerialName(value = "members")
    val members: kotlin.collections.List<GetContactList200ResponseMembersInner>? = null

) {


}

