/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param totalContacts 
 * @param internalUsers 
 * @param externalContacts 
 * @param syncedContacts 
 * @param sharedLists 
 * @param directoryGroups 
 */
@Serializable

data class GetDirectoryStats200Response (

    @SerialName(value = "total_contacts")
    val totalContacts: kotlin.Int? = null,

    @SerialName(value = "internal_users")
    val internalUsers: kotlin.Int? = null,

    @SerialName(value = "external_contacts")
    val externalContacts: kotlin.Int? = null,

    @SerialName(value = "synced_contacts")
    val syncedContacts: kotlin.Int? = null,

    @SerialName(value = "shared_lists")
    val sharedLists: kotlin.Int? = null,

    @SerialName(value = "directory_groups")
    val directoryGroups: kotlin.Int? = null

) {


}

