/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param message 
 * @param detail 
 * @param timestamp 
 */
@Serializable

data class GetDirectoryActivity200ResponseDataInner (

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null,

    @SerialName(value = "detail")
    val detail: kotlin.String? = null,

    @Contextual @SerialName(value = "timestamp")
    val timestamp: kotlin.time.Instant? = null

) {


}

