/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param key 
 * @param label 
 * @param status 
 */
@Serializable

data class GetDomainsStatus200ResponseDomainsInnerChecksInner (

    @SerialName(value = "key")
    val key: kotlin.String? = null,

    @SerialName(value = "label")
    val label: kotlin.String? = null,

    @SerialName(value = "status")
    val status: GetDomainsStatus200ResponseDomainsInnerChecksInner.Status? = null

) {

    /**
     * 
     *
     * Values: healthy,warning,critical
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "healthy") healthy("healthy"),
        @SerialName(value = "warning") warning("warning"),
        @SerialName(value = "critical") critical("critical");
    }

}

