/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param paused 
 * @param consecutiveFailures 
 * @param lastFailureAt 
 */
@Serializable

data class GetIntegrationsSummary200ResponseWebhooksInner (

    @Contextual @SerialName(value = "url")
    val url: java.net.URI? = null,

    @SerialName(value = "paused")
    val paused: kotlin.Boolean? = null,

    @SerialName(value = "consecutive_failures")
    val consecutiveFailures: kotlin.Int? = null,

    @Contextual @SerialName(value = "last_failure_at")
    val lastFailureAt: kotlin.time.Instant? = null

) {


}

