/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param domainId 
 * @param email 
 * @param quotaBytes 
 * @param disabled 
 * @param createdAt 
 * @param disabledAt 
 * @param softDeletedAt 
 * @param hardDeleteAfter 
 * @param password ONLY present on POST response when lockally generated the password. Shown once.
 */
@Serializable

data class Mailbox (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "tenant_id")
    val tenantId: java.util.UUID,

    @Contextual @SerialName(value = "domain_id")
    val domainId: java.util.UUID,

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "quota_bytes")
    val quotaBytes: kotlin.Long,

    @SerialName(value = "disabled")
    val disabled: kotlin.Boolean,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "disabled_at")
    val disabledAt: kotlin.time.Instant? = null,

    @Contextual @SerialName(value = "soft_deleted_at")
    val softDeletedAt: kotlin.time.Instant? = null,

    @Contextual @SerialName(value = "hard_delete_after")
    val hardDeleteAfter: kotlin.time.Instant? = null,

    /* ONLY present on POST response when lockally generated the password. Shown once. */
    @SerialName(value = "password")
    val password: kotlin.String? = null

) {


}

