/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param delivered 
 * @param bounced 
 * @param deferred 
 * @param complaint 
 */
@Serializable

data class MessageStatsCounts (

    @SerialName(value = "delivered")
    val delivered: kotlin.Int? = null,

    @SerialName(value = "bounced")
    val bounced: kotlin.Int? = null,

    @SerialName(value = "deferred")
    val deferred: kotlin.Int? = null,

    @SerialName(value = "complaint")
    val complaint: kotlin.Int? = null

) {


}

