/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import com.lockally.sdk.model.MessageStatsCounts
import com.lockally.sdk.model.MessageStatsRates
import com.lockally.sdk.model.MessageStatsWindow

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param window 
 * @param domain 
 * @param sent 
 * @param counts 
 * @param rates 
 */
@Serializable

data class MessageStats (

    @SerialName(value = "window")
    val window: MessageStatsWindow? = null,

    @SerialName(value = "domain")
    val domain: kotlin.String? = null,

    @SerialName(value = "sent")
    val sent: kotlin.Int? = null,

    @SerialName(value = "counts")
    val counts: MessageStatsCounts? = null,

    @SerialName(value = "rates")
    val rates: MessageStatsRates? = null

) {


}

