/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param messageId RFC 5322 Message-ID header, including angle brackets.
 * @param sender 
 * @param recipients 
 * @param status 
 * @param queuedAt 
 * @param updatedAt 
 * @param subject 
 * @param bounceReason 
 * @param sizeBytes 
 */
@Serializable

data class Message (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "tenant_id")
    val tenantId: java.util.UUID,

    /* RFC 5322 Message-ID header, including angle brackets. */
    @SerialName(value = "message_id")
    val messageId: kotlin.String,

    @SerialName(value = "sender")
    val sender: kotlin.String,

    @SerialName(value = "recipients")
    val recipients: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "status")
    val status: Message.Status,

    @Contextual @SerialName(value = "queued_at")
    val queuedAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.time.Instant,

    @SerialName(value = "subject")
    val subject: kotlin.String? = null,

    @SerialName(value = "bounce_reason")
    val bounceReason: kotlin.String? = null,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: queued,sending,delivered,bounced,deferred,complaint
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "queued") queued("queued"),
        @SerialName(value = "sending") sending("sending"),
        @SerialName(value = "delivered") delivered("delivered"),
        @SerialName(value = "bounced") bounced("bounced"),
        @SerialName(value = "deferred") deferred("deferred"),
        @SerialName(value = "complaint") complaint("complaint");
    }

}

