/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param migrationId 
 * @param tenantId 
 * @param eventType 
 * @param actor 
 * @param createdAt 
 * @param mailboxId 
 * @param oldStatus 
 * @param newStatus 
 * @param detail 
 */
@Serializable

data class MigrationEvent (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "migration_id")
    val migrationId: java.util.UUID,

    @Contextual @SerialName(value = "tenant_id")
    val tenantId: java.util.UUID,

    @SerialName(value = "event_type")
    val eventType: kotlin.String,

    @SerialName(value = "actor")
    val actor: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "mailbox_id")
    val mailboxId: java.util.UUID? = null,

    @SerialName(value = "old_status")
    val oldStatus: kotlin.String? = null,

    @SerialName(value = "new_status")
    val newStatus: kotlin.String? = null,

    @SerialName(value = "detail")
    val detail: kotlin.String? = null

) {


}

