/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import com.lockally.sdk.model.MigrationProgressMailboxesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param migrationId 
 * @param status 
 * @param totalMailboxes 
 * @param completedMailboxes 
 * @param failedMailboxes 
 * @param totalMessages 
 * @param syncedMessages 
 * @param failedMessages 
 * @param percentComplete 
 * @param mailboxes 
 */
@Serializable

data class MigrationProgress (

    @Contextual @SerialName(value = "migration_id")
    val migrationId: java.util.UUID,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "total_mailboxes")
    val totalMailboxes: kotlin.Int,

    @SerialName(value = "completed_mailboxes")
    val completedMailboxes: kotlin.Int,

    @SerialName(value = "failed_mailboxes")
    val failedMailboxes: kotlin.Int,

    @SerialName(value = "total_messages")
    val totalMessages: kotlin.Int,

    @SerialName(value = "synced_messages")
    val syncedMessages: kotlin.Int,

    @SerialName(value = "failed_messages")
    val failedMessages: kotlin.Int,

    @Contextual @SerialName(value = "percent_complete")
    val percentComplete: java.math.BigDecimal,

    @SerialName(value = "mailboxes")
    val mailboxes: kotlin.collections.List<MigrationProgressMailboxesInner>

) {


}

