/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param migrationId 
 * @param tenantId 
 * @param sourceEmail 
 * @param status 
 * @param syncedMessageCount 
 * @param failedMessageCount 
 * @param createdAt 
 * @param updatedAt 
 * @param destEmail 
 * @param destMailboxId 
 * @param sourceMessageCount 
 * @param sourceSizeBytes 
 * @param syncedSizeBytes 
 * @param lastSyncedUid 
 * @param lastSyncedAt 
 * @param errorMessage 
 * @param startedAt 
 * @param completedAt 
 */
@Serializable

data class MigrationMailbox (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "migration_id")
    val migrationId: java.util.UUID,

    @Contextual @SerialName(value = "tenant_id")
    val tenantId: java.util.UUID,

    @SerialName(value = "source_email")
    val sourceEmail: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "synced_message_count")
    val syncedMessageCount: kotlin.Int,

    @SerialName(value = "failed_message_count")
    val failedMessageCount: kotlin.Int,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.time.Instant,

    @SerialName(value = "dest_email")
    val destEmail: kotlin.String? = null,

    @Contextual @SerialName(value = "dest_mailbox_id")
    val destMailboxId: java.util.UUID? = null,

    @SerialName(value = "source_message_count")
    val sourceMessageCount: kotlin.Int? = null,

    @SerialName(value = "source_size_bytes")
    val sourceSizeBytes: kotlin.Long? = null,

    @SerialName(value = "synced_size_bytes")
    val syncedSizeBytes: kotlin.Long? = null,

    @SerialName(value = "last_synced_uid")
    val lastSyncedUid: kotlin.String? = null,

    @Contextual @SerialName(value = "last_synced_at")
    val lastSyncedAt: kotlin.time.Instant? = null,

    @SerialName(value = "error_message")
    val errorMessage: kotlin.String? = null,

    @Contextual @SerialName(value = "started_at")
    val startedAt: kotlin.time.Instant? = null,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: kotlin.time.Instant? = null

) {


}

