/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * RFC 9457 problem-details document.
 *
 * @param type 
 * @param status 
 * @param title 
 * @param detail 
 * @param instance 
 */
@Serializable

data class Problem (

    @Contextual @SerialName(value = "type")
    val type: java.net.URI = java.net.URI.create("about:blank"),

    @SerialName(value = "status")
    val status: kotlin.Int,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "detail")
    val detail: kotlin.String? = null,

    @Contextual @SerialName(value = "instance")
    val instance: java.net.URI? = null

) {


}

