/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param slug 
 * @param displayName 
 * @param status 
 * @param plan 
 * @param rateCapPerMin Per-tenant share of the per-VPS 5/min outbound cap (L6).
 * @param dailyMsgQuota 
 * @param adminEmail 
 * @param createdAt 
 * @param suspendedAt 
 * @param closedAt 
 * @param hardDeleteAfter 
 */
@Serializable

data class Tenant (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "slug")
    val slug: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "status")
    val status: Tenant.Status,

    @SerialName(value = "plan")
    val plan: kotlin.String,

    /* Per-tenant share of the per-VPS 5/min outbound cap (L6). */
    @SerialName(value = "rate_cap_per_min")
    val rateCapPerMin: kotlin.Int,

    @SerialName(value = "daily_msg_quota")
    val dailyMsgQuota: kotlin.Int,

    @SerialName(value = "admin_email")
    val adminEmail: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "suspended_at")
    val suspendedAt: kotlin.time.Instant? = null,

    @Contextual @SerialName(value = "closed_at")
    val closedAt: kotlin.time.Instant? = null,

    @Contextual @SerialName(value = "hard_delete_after")
    val hardDeleteAfter: kotlin.time.Instant? = null

) {

    /**
     * 
     *
     * Values: active,suspended,closing,closed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "active") active("active"),
        @SerialName(value = "suspended") suspended("suspended"),
        @SerialName(value = "closing") closing("closing"),
        @SerialName(value = "closed") closed("closed");
    }

}

