/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param type 
 * @param capacity 
 * @param status 
 */
@Serializable

data class UpdateResourceRequest (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "type")
    val type: UpdateResourceRequest.Type? = null,

    @SerialName(value = "capacity")
    val capacity: kotlin.Int? = null,

    @SerialName(value = "status")
    val status: UpdateResourceRequest.Status? = null

) {

    /**
     * 
     *
     * Values: meeting_room,equipment
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "meeting_room") meeting_room("meeting_room"),
        @SerialName(value = "equipment") equipment("equipment");
    }
    /**
     * 
     *
     * Values: available,active,disabled
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "available") available("available"),
        @SerialName(value = "active") active("active"),
        @SerialName(value = "disabled") disabled("disabled");
    }

}

