/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param maxMeetingDurationMins 
 * @param workingHoursStart 
 * @param workingHoursEnd 
 * @param bookingWindowDays 
 * @param recurringMeetingLimit 
 * @param resourceApprovalMode 
 * @param externalInvitesAllowed 
 * @param externalSharingAllowed 
 * @param publicLinksEnabled 
 */
@Serializable

data class UpdateCalendarPoliciesRequest (

    @SerialName(value = "max_meeting_duration_mins")
    val maxMeetingDurationMins: kotlin.Int? = null,

    @SerialName(value = "working_hours_start")
    val workingHoursStart: kotlin.String? = null,

    @SerialName(value = "working_hours_end")
    val workingHoursEnd: kotlin.String? = null,

    @SerialName(value = "booking_window_days")
    val bookingWindowDays: kotlin.Int? = null,

    @SerialName(value = "recurring_meeting_limit")
    val recurringMeetingLimit: kotlin.Int? = null,

    @SerialName(value = "resource_approval_mode")
    val resourceApprovalMode: UpdateCalendarPoliciesRequest.ResourceApprovalMode? = null,

    @SerialName(value = "external_invites_allowed")
    val externalInvitesAllowed: kotlin.Boolean? = null,

    @SerialName(value = "external_sharing_allowed")
    val externalSharingAllowed: kotlin.Boolean? = null,

    @SerialName(value = "public_links_enabled")
    val publicLinksEnabled: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: auto_approve,require_approval,restricted
     */
    @Serializable
    enum class ResourceApprovalMode(val value: kotlin.String) {
        @SerialName(value = "auto_approve") auto_approve("auto_approve"),
        @SerialName(value = "require_approval") require_approval("require_approval"),
        @SerialName(value = "restricted") restricted("restricted");
    }

}

