/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param role 
 */
@Serializable

data class UpdateCalendarMemberRequest (

    @SerialName(value = "role")
    val role: UpdateCalendarMemberRequest.Role

) {

    /**
     * 
     *
     * Values: viewer,editor,owner
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "viewer") viewer("viewer"),
        @SerialName(value = "editor") editor("editor"),
        @SerialName(value = "owner") owner("owner");
    }

}

