/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param label Free-text identifier shown in the dashboard.
 * @param scopes Allowed scopes on this key.
 */
@Serializable

data class V1ApiKeysPostRequest (

    /* Free-text identifier shown in the dashboard. */
    @SerialName(value = "label")
    val label: kotlin.String,

    /* Allowed scopes on this key. */
    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<V1ApiKeysPostRequest.Scopes>

) {

    /**
     * Allowed scopes on this key.
     *
     * Values: tenantColonRead,tenantColonAdmin,mailboxesColonRead,mailboxesColonWrite,sendColonRead,sendColonWrite,webhooksColonRead,webhooksColonWrite,domainsColonRead,domainsColonWrite
     */
    @Serializable
    enum class Scopes(val value: kotlin.String) {
        @SerialName(value = "tenant:read") tenantColonRead("tenant:read"),
        @SerialName(value = "tenant:admin") tenantColonAdmin("tenant:admin"),
        @SerialName(value = "mailboxes:read") mailboxesColonRead("mailboxes:read"),
        @SerialName(value = "mailboxes:write") mailboxesColonWrite("mailboxes:write"),
        @SerialName(value = "send:read") sendColonRead("send:read"),
        @SerialName(value = "send:write") sendColonWrite("send:write"),
        @SerialName(value = "webhooks:read") webhooksColonRead("webhooks:read"),
        @SerialName(value = "webhooks:write") webhooksColonWrite("webhooks:write"),
        @SerialName(value = "domains:read") domainsColonRead("domains:read"),
        @SerialName(value = "domains:write") domainsColonWrite("domains:write");
    }

}

