/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param password Optional; lockally generates if absent.
 * @param quotaBytes 5 GB default.
 */
@Serializable

data class V1MailboxesPostRequest (

    @SerialName(value = "email")
    val email: kotlin.String,

    /* Optional; lockally generates if absent. */
    @SerialName(value = "password")
    val password: kotlin.String? = null,

    /* 5 GB default. */
    @SerialName(value = "quota_bytes")
    val quotaBytes: kotlin.Long? = 5368709120L

) {


}

