/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import com.lockally.sdk.model.Message

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `data` 
 * @param nextCursor Pass as `cursor` to fetch the next page. Absent on the final page.
 */
@Serializable

data class V1MessagesGet200Response (

    @SerialName(value = "data")
    val `data`: kotlin.collections.List<Message>,

    /* Pass as `cursor` to fetch the next page. Absent on the final page. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

