/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Lockally identifier; use with GET /v1/messages/{id}.
 * @param messageId RFC 5322 Message-ID (with angle brackets).
 * @param status \"scheduled\" when send_at is in the future.
 * @param warning 
 */
@Serializable

data class V1SendPost202Response (

    /* Lockally identifier; use with GET /v1/messages/{id}. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* RFC 5322 Message-ID (with angle brackets). */
    @SerialName(value = "message_id")
    val messageId: kotlin.String,

    /* \"scheduled\" when send_at is in the future. */
    @SerialName(value = "status")
    val status: V1SendPost202Response.Status,

    @SerialName(value = "warning")
    val warning: kotlin.String? = null

) {

    /**
     * \"scheduled\" when send_at is in the future.
     *
     * Values: queued,scheduled
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "queued") queued("queued"),
        @SerialName(value = "scheduled") scheduled("scheduled");
    }

}

