/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import com.lockally.sdk.model.V1SendPostRequestAttachmentsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param from 
 * @param to 
 * @param cc 
 * @param bcc 
 * @param subject 
 * @param text Plain-text body. Required if `html` is absent.
 * @param html HTML body. Required if `text` is absent.
 * @param headers 
 * @param unsubscribe Mark as opt-in/broadcast: skips suppressed recipients and adds a managed one-click List-Unsubscribe header.
 * @param templateId Render subject/text/html from a stored template (GET /v1/templates). Mutually exclusive with inline subject/text/html.
 * @param variables Values substituted into the template's {{variable}} placeholders.
 * @param sendAt Schedule delivery for a future RFC3339 time (≤ 30 days out). Omit or past = send now. Cancel with DELETE /v1/messages/{id} while scheduled.
 * @param attachments 
 */
@Serializable

data class V1SendPostRequest (

    @SerialName(value = "from")
    val from: kotlin.String,

    @SerialName(value = "to")
    val to: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "cc")
    val cc: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "bcc")
    val bcc: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "subject")
    val subject: kotlin.String? = null,

    /* Plain-text body. Required if `html` is absent. */
    @SerialName(value = "text")
    val text: kotlin.String? = null,

    /* HTML body. Required if `text` is absent. */
    @SerialName(value = "html")
    val html: kotlin.String? = null,

    @SerialName(value = "headers")
    val headers: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Mark as opt-in/broadcast: skips suppressed recipients and adds a managed one-click List-Unsubscribe header. */
    @SerialName(value = "unsubscribe")
    val unsubscribe: kotlin.Boolean? = null,

    /* Render subject/text/html from a stored template (GET /v1/templates). Mutually exclusive with inline subject/text/html. */
    @Contextual @SerialName(value = "template_id")
    val templateId: java.util.UUID? = null,

    /* Values substituted into the template's {{variable}} placeholders. */
    @SerialName(value = "variables")
    val variables: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Schedule delivery for a future RFC3339 time (≤ 30 days out). Omit or past = send now. Cancel with DELETE /v1/messages/{id} while scheduled. */
    @Contextual @SerialName(value = "send_at")
    val sendAt: kotlin.time.Instant? = null,

    @SerialName(value = "attachments")
    val attachments: kotlin.collections.List<V1SendPostRequestAttachmentsInner>? = null

) {


}

