/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import com.lockally.sdk.model.VacationParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param mailboxEmail 
 * @param enabled 
 * @param params 
 * @param script Pre-rendered Sieve script (RFC 5230).
 * @param createdAt 
 * @param updatedAt 
 * @param syncedAt Null = stored on lockally but not yet pushed to the mail server.
 */
@Serializable

data class VacationResponder (

    @SerialName(value = "mailbox_email")
    val mailboxEmail: kotlin.String,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @SerialName(value = "params")
    val params: VacationParams,

    /* Pre-rendered Sieve script (RFC 5230). */
    @SerialName(value = "script")
    val script: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: kotlin.time.Instant,

    /* Null = stored on lockally but not yet pushed to the mail server. */
    @Contextual @SerialName(value = "synced_at")
    val syncedAt: kotlin.time.Instant? = null

) {


}

