/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param tenantId 
 * @param url 
 * @param events 
 * @param paused 
 * @param consecutiveFailures 
 * @param createdAt 
 * @param pausedAt 
 * @param lastSuccessAt 
 * @param lastFailureAt 
 * @param signingSecret Hex-encoded HMAC-SHA256 key. Present ONLY on POST response.
 */
@Serializable

data class Webhook (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "tenant_id")
    val tenantId: java.util.UUID,

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "paused")
    val paused: kotlin.Boolean,

    @SerialName(value = "consecutive_failures")
    val consecutiveFailures: kotlin.Int,

    @Contextual @SerialName(value = "created_at")
    val createdAt: kotlin.time.Instant,

    @Contextual @SerialName(value = "paused_at")
    val pausedAt: kotlin.time.Instant? = null,

    @Contextual @SerialName(value = "last_success_at")
    val lastSuccessAt: kotlin.time.Instant? = null,

    @Contextual @SerialName(value = "last_failure_at")
    val lastFailureAt: kotlin.time.Instant? = null,

    /* Hex-encoded HMAC-SHA256 key. Present ONLY on POST response. */
    @SerialName(value = "signing_secret")
    val signingSecret: kotlin.String? = null

) {


}

