/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.lockally.sdk.model.DirectoryPermissions
import com.lockally.sdk.model.GALSettings
import com.lockally.sdk.model.GetDirectoryActivity200Response
import com.lockally.sdk.model.GetDirectoryStats200Response
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.UpdateDirectoryPermissionsRequest
import com.lockally.sdk.model.UpdateGALSettingsRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.lockally.sdk.infrastructure.ApiClient
import com.lockally.sdk.infrastructure.ApiResponse
import com.lockally.sdk.infrastructure.ClientException
import com.lockally.sdk.infrastructure.ClientError
import com.lockally.sdk.infrastructure.ServerException
import com.lockally.sdk.infrastructure.ServerError
import com.lockally.sdk.infrastructure.MultiValueMap
import com.lockally.sdk.infrastructure.PartConfig
import com.lockally.sdk.infrastructure.RequestConfig
import com.lockally.sdk.infrastructure.RequestMethod
import com.lockally.sdk.infrastructure.ResponseType
import com.lockally.sdk.infrastructure.Success
import com.lockally.sdk.infrastructure.toMultiValue
import com.lockally.sdk.infrastructure.Serializer

open class DirectoryApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.lockally.com")
        }
    }

    /**
     * GET /v1/directory-activity
     * Get recent directory activity
     * 
     * @return GetDirectoryActivity200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getDirectoryActivity() : GetDirectoryActivity200Response = withContext(Dispatchers.IO) {
        val localVarResponse = getDirectoryActivityWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetDirectoryActivity200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/directory-activity
     * Get recent directory activity
     * 
     * @return ApiResponse<GetDirectoryActivity200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getDirectoryActivityWithHttpInfo() : ApiResponse<GetDirectoryActivity200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getDirectoryActivityRequestConfig()

        return@withContext request<Unit, GetDirectoryActivity200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getDirectoryActivity
     *
     * @return RequestConfig
     */
    fun getDirectoryActivityRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/directory-activity",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/directory-permissions
     * Get directory permission settings
     * 
     * @return DirectoryPermissions
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getDirectoryPermissions() : DirectoryPermissions = withContext(Dispatchers.IO) {
        val localVarResponse = getDirectoryPermissionsWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DirectoryPermissions
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/directory-permissions
     * Get directory permission settings
     * 
     * @return ApiResponse<DirectoryPermissions?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getDirectoryPermissionsWithHttpInfo() : ApiResponse<DirectoryPermissions?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getDirectoryPermissionsRequestConfig()

        return@withContext request<Unit, DirectoryPermissions>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getDirectoryPermissions
     *
     * @return RequestConfig
     */
    fun getDirectoryPermissionsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/directory-permissions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/directory-stats
     * Get directory statistics
     * 
     * @return GetDirectoryStats200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getDirectoryStats() : GetDirectoryStats200Response = withContext(Dispatchers.IO) {
        val localVarResponse = getDirectoryStatsWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetDirectoryStats200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/directory-stats
     * Get directory statistics
     * 
     * @return ApiResponse<GetDirectoryStats200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getDirectoryStatsWithHttpInfo() : ApiResponse<GetDirectoryStats200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getDirectoryStatsRequestConfig()

        return@withContext request<Unit, GetDirectoryStats200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getDirectoryStats
     *
     * @return RequestConfig
     */
    fun getDirectoryStatsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/directory-stats",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/gal-settings
     * Get Global Address List settings
     * 
     * @return GALSettings
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getGALSettings() : GALSettings = withContext(Dispatchers.IO) {
        val localVarResponse = getGALSettingsWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GALSettings
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/gal-settings
     * Get Global Address List settings
     * 
     * @return ApiResponse<GALSettings?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getGALSettingsWithHttpInfo() : ApiResponse<GALSettings?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getGALSettingsRequestConfig()

        return@withContext request<Unit, GALSettings>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getGALSettings
     *
     * @return RequestConfig
     */
    fun getGALSettingsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/gal-settings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/gal-settings/rebuild-index
     * Rebuild the GAL search index
     * 
     * @return GALSettings
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun rebuildGALIndex() : GALSettings = withContext(Dispatchers.IO) {
        val localVarResponse = rebuildGALIndexWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GALSettings
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/gal-settings/rebuild-index
     * Rebuild the GAL search index
     * 
     * @return ApiResponse<GALSettings?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun rebuildGALIndexWithHttpInfo() : ApiResponse<GALSettings?> = withContext(Dispatchers.IO) {
        val localVariableConfig = rebuildGALIndexRequestConfig()

        return@withContext request<Unit, GALSettings>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation rebuildGALIndex
     *
     * @return RequestConfig
     */
    fun rebuildGALIndexRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/gal-settings/rebuild-index",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/gal-settings/sync
     * Sync GAL with external directory sources
     * 
     * @return GALSettings
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun syncGAL() : GALSettings = withContext(Dispatchers.IO) {
        val localVarResponse = syncGALWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GALSettings
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/gal-settings/sync
     * Sync GAL with external directory sources
     * 
     * @return ApiResponse<GALSettings?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun syncGALWithHttpInfo() : ApiResponse<GALSettings?> = withContext(Dispatchers.IO) {
        val localVariableConfig = syncGALRequestConfig()

        return@withContext request<Unit, GALSettings>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation syncGAL
     *
     * @return RequestConfig
     */
    fun syncGALRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/gal-settings/sync",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/directory-permissions
     * Update directory permission settings
     * 
     * @param updateDirectoryPermissionsRequest 
     * @return DirectoryPermissions
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateDirectoryPermissions(updateDirectoryPermissionsRequest: UpdateDirectoryPermissionsRequest) : DirectoryPermissions = withContext(Dispatchers.IO) {
        val localVarResponse = updateDirectoryPermissionsWithHttpInfo(updateDirectoryPermissionsRequest = updateDirectoryPermissionsRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DirectoryPermissions
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/directory-permissions
     * Update directory permission settings
     * 
     * @param updateDirectoryPermissionsRequest 
     * @return ApiResponse<DirectoryPermissions?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateDirectoryPermissionsWithHttpInfo(updateDirectoryPermissionsRequest: UpdateDirectoryPermissionsRequest) : ApiResponse<DirectoryPermissions?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateDirectoryPermissionsRequestConfig(updateDirectoryPermissionsRequest = updateDirectoryPermissionsRequest)

        return@withContext request<UpdateDirectoryPermissionsRequest, DirectoryPermissions>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateDirectoryPermissions
     *
     * @param updateDirectoryPermissionsRequest 
     * @return RequestConfig
     */
    fun updateDirectoryPermissionsRequestConfig(updateDirectoryPermissionsRequest: UpdateDirectoryPermissionsRequest) : RequestConfig<UpdateDirectoryPermissionsRequest> {
        val localVariableBody = updateDirectoryPermissionsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/directory-permissions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/gal-settings
     * Update GAL settings
     * 
     * @param updateGALSettingsRequest 
     * @return GALSettings
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateGALSettings(updateGALSettingsRequest: UpdateGALSettingsRequest) : GALSettings = withContext(Dispatchers.IO) {
        val localVarResponse = updateGALSettingsWithHttpInfo(updateGALSettingsRequest = updateGALSettingsRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GALSettings
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/gal-settings
     * Update GAL settings
     * 
     * @param updateGALSettingsRequest 
     * @return ApiResponse<GALSettings?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateGALSettingsWithHttpInfo(updateGALSettingsRequest: UpdateGALSettingsRequest) : ApiResponse<GALSettings?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateGALSettingsRequestConfig(updateGALSettingsRequest = updateGALSettingsRequest)

        return@withContext request<UpdateGALSettingsRequest, GALSettings>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateGALSettings
     *
     * @param updateGALSettingsRequest 
     * @return RequestConfig
     */
    fun updateGALSettingsRequestConfig(updateGALSettingsRequest: UpdateGALSettingsRequest) : RequestConfig<UpdateGALSettingsRequest> {
        val localVariableBody = updateGALSettingsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/gal-settings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
