/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.lockally.sdk.model.AddSharedMemberRequest
import com.lockally.sdk.model.ListSharedMembers200Response
import com.lockally.sdk.model.Mailbox
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.SharedMember
import com.lockally.sdk.model.V1MailboxesEmailExportPost201Response
import com.lockally.sdk.model.V1MailboxesEmailPatchRequest
import com.lockally.sdk.model.V1MailboxesEmailVacationPutRequest
import com.lockally.sdk.model.V1MailboxesGet200Response
import com.lockally.sdk.model.V1MailboxesPostRequest
import com.lockally.sdk.model.V1VacationGet200Response
import com.lockally.sdk.model.VacationResponder

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.lockally.sdk.infrastructure.ApiClient
import com.lockally.sdk.infrastructure.ApiResponse
import com.lockally.sdk.infrastructure.ClientException
import com.lockally.sdk.infrastructure.ClientError
import com.lockally.sdk.infrastructure.ServerException
import com.lockally.sdk.infrastructure.ServerError
import com.lockally.sdk.infrastructure.MultiValueMap
import com.lockally.sdk.infrastructure.PartConfig
import com.lockally.sdk.infrastructure.RequestConfig
import com.lockally.sdk.infrastructure.RequestMethod
import com.lockally.sdk.infrastructure.ResponseType
import com.lockally.sdk.infrastructure.Success
import com.lockally.sdk.infrastructure.toMultiValue
import com.lockally.sdk.infrastructure.Serializer

open class MailboxesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.lockally.com")
        }
    }

    /**
     * POST /v1/mailboxes/{email}/members
     * Add a shared mailbox member
     * 
     * @param email 
     * @param addSharedMemberRequest 
     * @return SharedMember
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun addSharedMember(email: kotlin.String, addSharedMemberRequest: AddSharedMemberRequest) : SharedMember = withContext(Dispatchers.IO) {
        val localVarResponse = addSharedMemberWithHttpInfo(email = email, addSharedMemberRequest = addSharedMemberRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SharedMember
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/mailboxes/{email}/members
     * Add a shared mailbox member
     * 
     * @param email 
     * @param addSharedMemberRequest 
     * @return ApiResponse<SharedMember?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun addSharedMemberWithHttpInfo(email: kotlin.String, addSharedMemberRequest: AddSharedMemberRequest) : ApiResponse<SharedMember?> = withContext(Dispatchers.IO) {
        val localVariableConfig = addSharedMemberRequestConfig(email = email, addSharedMemberRequest = addSharedMemberRequest)

        return@withContext request<AddSharedMemberRequest, SharedMember>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation addSharedMember
     *
     * @param email 
     * @param addSharedMemberRequest 
     * @return RequestConfig
     */
    fun addSharedMemberRequestConfig(email: kotlin.String, addSharedMemberRequest: AddSharedMemberRequest) : RequestConfig<AddSharedMemberRequest> {
        val localVariableBody = addSharedMemberRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/mailboxes/{email}/members".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/mailboxes/{email}/members
     * List shared mailbox members
     * 
     * @param email 
     * @return ListSharedMembers200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listSharedMembers(email: kotlin.String) : ListSharedMembers200Response = withContext(Dispatchers.IO) {
        val localVarResponse = listSharedMembersWithHttpInfo(email = email)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListSharedMembers200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/mailboxes/{email}/members
     * List shared mailbox members
     * 
     * @param email 
     * @return ApiResponse<ListSharedMembers200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listSharedMembersWithHttpInfo(email: kotlin.String) : ApiResponse<ListSharedMembers200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listSharedMembersRequestConfig(email = email)

        return@withContext request<Unit, ListSharedMembers200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listSharedMembers
     *
     * @param email 
     * @return RequestConfig
     */
    fun listSharedMembersRequestConfig(email: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/mailboxes/{email}/members".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/mailboxes/{email}/members/{memberEmail}
     * Remove a shared mailbox member
     * 
     * @param email 
     * @param memberEmail 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun removeSharedMember(email: kotlin.String, memberEmail: kotlin.String) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = removeSharedMemberWithHttpInfo(email = email, memberEmail = memberEmail)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/mailboxes/{email}/members/{memberEmail}
     * Remove a shared mailbox member
     * 
     * @param email 
     * @param memberEmail 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun removeSharedMemberWithHttpInfo(email: kotlin.String, memberEmail: kotlin.String) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = removeSharedMemberRequestConfig(email = email, memberEmail = memberEmail)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation removeSharedMember
     *
     * @param email 
     * @param memberEmail 
     * @return RequestConfig
     */
    fun removeSharedMemberRequestConfig(email: kotlin.String, memberEmail: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/problem+json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/mailboxes/{email}/members/{memberEmail}".replace("{"+"email"+"}", encodeURIComponent(email.toString())).replace("{"+"memberEmail"+"}", encodeURIComponent(memberEmail.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/mailboxes/{email}
     * Soft-delete a mailbox
     * Sets &#x60;soft_deleted_at &#x3D; now()&#x60; and &#x60;hard_delete_after &#x3D; now() + 90d&#x60; per design D25. A background sweep (planned) will hard-delete after the window. The mailbox is also disabled immediately. 
     * @param email 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesEmailDelete(email: kotlin.String) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesEmailDeleteWithHttpInfo(email = email)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/mailboxes/{email}
     * Soft-delete a mailbox
     * Sets &#x60;soft_deleted_at &#x3D; now()&#x60; and &#x60;hard_delete_after &#x3D; now() + 90d&#x60; per design D25. A background sweep (planned) will hard-delete after the window. The mailbox is also disabled immediately. 
     * @param email 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesEmailDeleteWithHttpInfo(email: kotlin.String) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesEmailDeleteRequestConfig(email = email)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesEmailDelete
     *
     * @param email 
     * @return RequestConfig
     */
    fun v1MailboxesEmailDeleteRequestConfig(email: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/problem+json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/mailboxes/{email}".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/mailboxes/{email}/export/download
     * Download a previously-issued mailbox export
     * Public endpoint (no Authorization header). Validates the one-shot token from the URL, marks it used, and streams an mbox file. Second GET with the same token returns 404 — tokens are single-use. 
     * @param email 
     * @param token 
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesEmailExportDownloadGet(email: kotlin.String, token: kotlin.String) : java.io.File = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesEmailExportDownloadGetWithHttpInfo(email = email, token = token)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/mailboxes/{email}/export/download
     * Download a previously-issued mailbox export
     * Public endpoint (no Authorization header). Validates the one-shot token from the URL, marks it used, and streams an mbox file. Second GET with the same token returns 404 — tokens are single-use. 
     * @param email 
     * @param token 
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesEmailExportDownloadGetWithHttpInfo(email: kotlin.String, token: kotlin.String) : ApiResponse<java.io.File?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesEmailExportDownloadGetRequestConfig(email = email, token = token)

        return@withContext request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesEmailExportDownloadGet
     *
     * @param email 
     * @param token 
     * @return RequestConfig
     */
    fun v1MailboxesEmailExportDownloadGetRequestConfig(email: kotlin.String, token: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("token", listOf(token.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/mailboxes/{email}/export/download".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/mailboxes/{email}/export
     * Request a mailbox export
     * Issues a one-shot \&quot;presigned\&quot; download URL for the mailbox&#39;s content in mbox format. The URL works without an Authorization header — the token in the query string is the authz. TTL is 5 minutes; the token is consumed on first GET.  **v1 caveat:** the synthesized mbox only contains outbound mail (from &#x60;lockally.messages&#x60;). v2 swaps in Stalwart&#39;s export primitive for full inbox + folder structure + flags. The endpoint contract stays unchanged. 
     * @param email 
     * @return V1MailboxesEmailExportPost201Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesEmailExportPost(email: kotlin.String) : V1MailboxesEmailExportPost201Response = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesEmailExportPostWithHttpInfo(email = email)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1MailboxesEmailExportPost201Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/mailboxes/{email}/export
     * Request a mailbox export
     * Issues a one-shot \&quot;presigned\&quot; download URL for the mailbox&#39;s content in mbox format. The URL works without an Authorization header — the token in the query string is the authz. TTL is 5 minutes; the token is consumed on first GET.  **v1 caveat:** the synthesized mbox only contains outbound mail (from &#x60;lockally.messages&#x60;). v2 swaps in Stalwart&#39;s export primitive for full inbox + folder structure + flags. The endpoint contract stays unchanged. 
     * @param email 
     * @return ApiResponse<V1MailboxesEmailExportPost201Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesEmailExportPostWithHttpInfo(email: kotlin.String) : ApiResponse<V1MailboxesEmailExportPost201Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesEmailExportPostRequestConfig(email = email)

        return@withContext request<Unit, V1MailboxesEmailExportPost201Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesEmailExportPost
     *
     * @param email 
     * @return RequestConfig
     */
    fun v1MailboxesEmailExportPostRequestConfig(email: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/mailboxes/{email}/export".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/mailboxes/{email}
     * Get a mailbox
     * 
     * @param email 
     * @return Mailbox
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesEmailGet(email: kotlin.String) : Mailbox = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesEmailGetWithHttpInfo(email = email)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Mailbox
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/mailboxes/{email}
     * Get a mailbox
     * 
     * @param email 
     * @return ApiResponse<Mailbox?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesEmailGetWithHttpInfo(email: kotlin.String) : ApiResponse<Mailbox?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesEmailGetRequestConfig(email = email)

        return@withContext request<Unit, Mailbox>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesEmailGet
     *
     * @param email 
     * @return RequestConfig
     */
    fun v1MailboxesEmailGetRequestConfig(email: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/mailboxes/{email}".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/mailboxes/{email}
     * Update a mailbox
     * Supply at least one of &#x60;password&#x60;, &#x60;quota_bytes&#x60;, &#x60;disabled&#x60;. Returns the updated mailbox. 
     * @param email 
     * @param v1MailboxesEmailPatchRequest 
     * @return Mailbox
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesEmailPatch(email: kotlin.String, v1MailboxesEmailPatchRequest: V1MailboxesEmailPatchRequest) : Mailbox = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesEmailPatchWithHttpInfo(email = email, v1MailboxesEmailPatchRequest = v1MailboxesEmailPatchRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Mailbox
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/mailboxes/{email}
     * Update a mailbox
     * Supply at least one of &#x60;password&#x60;, &#x60;quota_bytes&#x60;, &#x60;disabled&#x60;. Returns the updated mailbox. 
     * @param email 
     * @param v1MailboxesEmailPatchRequest 
     * @return ApiResponse<Mailbox?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesEmailPatchWithHttpInfo(email: kotlin.String, v1MailboxesEmailPatchRequest: V1MailboxesEmailPatchRequest) : ApiResponse<Mailbox?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesEmailPatchRequestConfig(email = email, v1MailboxesEmailPatchRequest = v1MailboxesEmailPatchRequest)

        return@withContext request<V1MailboxesEmailPatchRequest, Mailbox>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesEmailPatch
     *
     * @param email 
     * @param v1MailboxesEmailPatchRequest 
     * @return RequestConfig
     */
    fun v1MailboxesEmailPatchRequestConfig(email: kotlin.String, v1MailboxesEmailPatchRequest: V1MailboxesEmailPatchRequest) : RequestConfig<V1MailboxesEmailPatchRequest> {
        val localVariableBody = v1MailboxesEmailPatchRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/mailboxes/{email}".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/mailboxes/{email}/vacation
     * Remove the vacation responder
     * Idempotent — 204 whether or not a row existed.
     * @param email 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesEmailVacationDelete(email: kotlin.String) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesEmailVacationDeleteWithHttpInfo(email = email)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/mailboxes/{email}/vacation
     * Remove the vacation responder
     * Idempotent — 204 whether or not a row existed.
     * @param email 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesEmailVacationDeleteWithHttpInfo(email: kotlin.String) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesEmailVacationDeleteRequestConfig(email = email)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesEmailVacationDelete
     *
     * @param email 
     * @return RequestConfig
     */
    fun v1MailboxesEmailVacationDeleteRequestConfig(email: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/problem+json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/mailboxes/{email}/vacation".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/mailboxes/{email}/vacation
     * Get the vacation responder
     * Returns the stored vacation rule or 404 if none is set.
     * @param email 
     * @return VacationResponder
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesEmailVacationGet(email: kotlin.String) : VacationResponder = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesEmailVacationGetWithHttpInfo(email = email)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as VacationResponder
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/mailboxes/{email}/vacation
     * Get the vacation responder
     * Returns the stored vacation rule or 404 if none is set.
     * @param email 
     * @return ApiResponse<VacationResponder?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesEmailVacationGetWithHttpInfo(email: kotlin.String) : ApiResponse<VacationResponder?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesEmailVacationGetRequestConfig(email = email)

        return@withContext request<Unit, VacationResponder>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesEmailVacationGet
     *
     * @param email 
     * @return RequestConfig
     */
    fun v1MailboxesEmailVacationGetRequestConfig(email: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/mailboxes/{email}/vacation".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /v1/mailboxes/{email}/vacation
     * Set the vacation responder
     * Upsert — same endpoint creates or replaces the rule. Clears &#x60;synced_at&#x60;; the rule is staged on lockally until a sync worker pushes it to the mail server. 
     * @param email 
     * @param v1MailboxesEmailVacationPutRequest 
     * @return VacationResponder
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesEmailVacationPut(email: kotlin.String, v1MailboxesEmailVacationPutRequest: V1MailboxesEmailVacationPutRequest) : VacationResponder = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesEmailVacationPutWithHttpInfo(email = email, v1MailboxesEmailVacationPutRequest = v1MailboxesEmailVacationPutRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as VacationResponder
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /v1/mailboxes/{email}/vacation
     * Set the vacation responder
     * Upsert — same endpoint creates or replaces the rule. Clears &#x60;synced_at&#x60;; the rule is staged on lockally until a sync worker pushes it to the mail server. 
     * @param email 
     * @param v1MailboxesEmailVacationPutRequest 
     * @return ApiResponse<VacationResponder?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesEmailVacationPutWithHttpInfo(email: kotlin.String, v1MailboxesEmailVacationPutRequest: V1MailboxesEmailVacationPutRequest) : ApiResponse<VacationResponder?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesEmailVacationPutRequestConfig(email = email, v1MailboxesEmailVacationPutRequest = v1MailboxesEmailVacationPutRequest)

        return@withContext request<V1MailboxesEmailVacationPutRequest, VacationResponder>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesEmailVacationPut
     *
     * @param email 
     * @param v1MailboxesEmailVacationPutRequest 
     * @return RequestConfig
     */
    fun v1MailboxesEmailVacationPutRequestConfig(email: kotlin.String, v1MailboxesEmailVacationPutRequest: V1MailboxesEmailVacationPutRequest) : RequestConfig<V1MailboxesEmailVacationPutRequest> {
        val localVariableBody = v1MailboxesEmailVacationPutRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/v1/mailboxes/{email}/vacation".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/mailboxes
     * List mailboxes
     * Returns mailboxes under the calling tenant — active and soft-deleted. &#x60;?limit&#x3D;N&#x60; between 1 and 200 (default 50). 
     * @param limit  (optional, default to 50)
     * @return V1MailboxesGet200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesGet(limit: kotlin.Int? = 50) : V1MailboxesGet200Response = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesGetWithHttpInfo(limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1MailboxesGet200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/mailboxes
     * List mailboxes
     * Returns mailboxes under the calling tenant — active and soft-deleted. &#x60;?limit&#x3D;N&#x60; between 1 and 200 (default 50). 
     * @param limit  (optional, default to 50)
     * @return ApiResponse<V1MailboxesGet200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesGetWithHttpInfo(limit: kotlin.Int?) : ApiResponse<V1MailboxesGet200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesGetRequestConfig(limit = limit)

        return@withContext request<Unit, V1MailboxesGet200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesGet
     *
     * @param limit  (optional, default to 50)
     * @return RequestConfig
     */
    fun v1MailboxesGetRequestConfig(limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/mailboxes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/mailboxes
     * Create a mailbox
     * Creates a mailbox on a tenant-verified domain. If &#x60;password&#x60; is omitted, lockally generates a 16-char password and returns it in the response — shown once.  **Gate.** The mailbox&#39;s domain must already be registered AND verified for this tenant (via &#x60;/v1/domains&#x60; + &#x60;/v1/domains/{domain}/verify&#x60;).  **Idempotent.** Re-posting the same email returns the existing mailbox UNTOUCHED — password is NOT regenerated. To change a password, use PATCH instead. 
     * @param v1MailboxesPostRequest 
     * @return Mailbox
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1MailboxesPost(v1MailboxesPostRequest: V1MailboxesPostRequest) : Mailbox = withContext(Dispatchers.IO) {
        val localVarResponse = v1MailboxesPostWithHttpInfo(v1MailboxesPostRequest = v1MailboxesPostRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Mailbox
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/mailboxes
     * Create a mailbox
     * Creates a mailbox on a tenant-verified domain. If &#x60;password&#x60; is omitted, lockally generates a 16-char password and returns it in the response — shown once.  **Gate.** The mailbox&#39;s domain must already be registered AND verified for this tenant (via &#x60;/v1/domains&#x60; + &#x60;/v1/domains/{domain}/verify&#x60;).  **Idempotent.** Re-posting the same email returns the existing mailbox UNTOUCHED — password is NOT regenerated. To change a password, use PATCH instead. 
     * @param v1MailboxesPostRequest 
     * @return ApiResponse<Mailbox?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1MailboxesPostWithHttpInfo(v1MailboxesPostRequest: V1MailboxesPostRequest) : ApiResponse<Mailbox?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1MailboxesPostRequestConfig(v1MailboxesPostRequest = v1MailboxesPostRequest)

        return@withContext request<V1MailboxesPostRequest, Mailbox>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1MailboxesPost
     *
     * @param v1MailboxesPostRequest 
     * @return RequestConfig
     */
    fun v1MailboxesPostRequestConfig(v1MailboxesPostRequest: V1MailboxesPostRequest) : RequestConfig<V1MailboxesPostRequest> {
        val localVariableBody = v1MailboxesPostRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/mailboxes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/vacation
     * List all vacation responders
     * Returns every vacation responder for the calling tenant.
     * @return V1VacationGet200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1VacationGet() : V1VacationGet200Response = withContext(Dispatchers.IO) {
        val localVarResponse = v1VacationGetWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1VacationGet200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/vacation
     * List all vacation responders
     * Returns every vacation responder for the calling tenant.
     * @return ApiResponse<V1VacationGet200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1VacationGetWithHttpInfo() : ApiResponse<V1VacationGet200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1VacationGetRequestConfig()

        return@withContext request<Unit, V1VacationGet200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1VacationGet
     *
     * @return RequestConfig
     */
    fun v1VacationGetRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/vacation",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
