/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.Suppression
import com.lockally.sdk.model.V1SuppressionsGet200Response
import com.lockally.sdk.model.V1SuppressionsPostRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.lockally.sdk.infrastructure.ApiClient
import com.lockally.sdk.infrastructure.ApiResponse
import com.lockally.sdk.infrastructure.ClientException
import com.lockally.sdk.infrastructure.ClientError
import com.lockally.sdk.infrastructure.ServerException
import com.lockally.sdk.infrastructure.ServerError
import com.lockally.sdk.infrastructure.MultiValueMap
import com.lockally.sdk.infrastructure.PartConfig
import com.lockally.sdk.infrastructure.RequestConfig
import com.lockally.sdk.infrastructure.RequestMethod
import com.lockally.sdk.infrastructure.ResponseType
import com.lockally.sdk.infrastructure.Success
import com.lockally.sdk.infrastructure.toMultiValue
import com.lockally.sdk.infrastructure.Serializer

open class SuppressionsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.lockally.com")
        }
    }

    /**
     * DELETE /v1/suppressions/{email}
     * Remove a suppression
     * 
     * @param email 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1SuppressionsEmailDelete(email: kotlin.String) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = v1SuppressionsEmailDeleteWithHttpInfo(email = email)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/suppressions/{email}
     * Remove a suppression
     * 
     * @param email 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1SuppressionsEmailDeleteWithHttpInfo(email: kotlin.String) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1SuppressionsEmailDeleteRequestConfig(email = email)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1SuppressionsEmailDelete
     *
     * @param email 
     * @return RequestConfig
     */
    fun v1SuppressionsEmailDeleteRequestConfig(email: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/problem+json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/suppressions/{email}".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/suppressions/{email}
     * Check whether an address is suppressed
     * 
     * @param email 
     * @return Suppression
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1SuppressionsEmailGet(email: kotlin.String) : Suppression = withContext(Dispatchers.IO) {
        val localVarResponse = v1SuppressionsEmailGetWithHttpInfo(email = email)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Suppression
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/suppressions/{email}
     * Check whether an address is suppressed
     * 
     * @param email 
     * @return ApiResponse<Suppression?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1SuppressionsEmailGetWithHttpInfo(email: kotlin.String) : ApiResponse<Suppression?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1SuppressionsEmailGetRequestConfig(email = email)

        return@withContext request<Unit, Suppression>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1SuppressionsEmailGet
     *
     * @param email 
     * @return RequestConfig
     */
    fun v1SuppressionsEmailGetRequestConfig(email: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/suppressions/{email}".replace("{"+"email"+"}", encodeURIComponent(email.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter reason
     */
     enum class ReasonV1SuppressionsGet(val value: kotlin.String) {
         @SerialName(value = "unsubscribe") unsubscribe("unsubscribe"),
         @SerialName(value = "complaint") complaint("complaint"),
         @SerialName(value = "bounce") bounce("bounce"),
         @SerialName(value = "manual") manual("manual");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /v1/suppressions
     * List suppressed recipients
     * 
     * @param reason  (optional)
     * @param cursor  (optional)
     * @param limit  (optional, default to 50)
     * @return V1SuppressionsGet200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1SuppressionsGet(reason: ReasonV1SuppressionsGet? = null, cursor: kotlin.String? = null, limit: kotlin.Int? = 50) : V1SuppressionsGet200Response = withContext(Dispatchers.IO) {
        val localVarResponse = v1SuppressionsGetWithHttpInfo(reason = reason, cursor = cursor, limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1SuppressionsGet200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/suppressions
     * List suppressed recipients
     * 
     * @param reason  (optional)
     * @param cursor  (optional)
     * @param limit  (optional, default to 50)
     * @return ApiResponse<V1SuppressionsGet200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1SuppressionsGetWithHttpInfo(reason: ReasonV1SuppressionsGet?, cursor: kotlin.String?, limit: kotlin.Int?) : ApiResponse<V1SuppressionsGet200Response?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1SuppressionsGetRequestConfig(reason = reason, cursor = cursor, limit = limit)

        return@withContext request<Unit, V1SuppressionsGet200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1SuppressionsGet
     *
     * @param reason  (optional)
     * @param cursor  (optional)
     * @param limit  (optional, default to 50)
     * @return RequestConfig
     */
    fun v1SuppressionsGetRequestConfig(reason: ReasonV1SuppressionsGet?, cursor: kotlin.String?, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (reason != null) {
                    put("reason", listOf(reason.value))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/suppressions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/suppressions
     * Add a suppression
     * 
     * @param v1SuppressionsPostRequest 
     * @return Suppression
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun v1SuppressionsPost(v1SuppressionsPostRequest: V1SuppressionsPostRequest) : Suppression = withContext(Dispatchers.IO) {
        val localVarResponse = v1SuppressionsPostWithHttpInfo(v1SuppressionsPostRequest = v1SuppressionsPostRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Suppression
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/suppressions
     * Add a suppression
     * 
     * @param v1SuppressionsPostRequest 
     * @return ApiResponse<Suppression?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun v1SuppressionsPostWithHttpInfo(v1SuppressionsPostRequest: V1SuppressionsPostRequest) : ApiResponse<Suppression?> = withContext(Dispatchers.IO) {
        val localVariableConfig = v1SuppressionsPostRequestConfig(v1SuppressionsPostRequest = v1SuppressionsPostRequest)

        return@withContext request<V1SuppressionsPostRequest, Suppression>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation v1SuppressionsPost
     *
     * @param v1SuppressionsPostRequest 
     * @return RequestConfig
     */
    fun v1SuppressionsPostRequestConfig(v1SuppressionsPostRequest: V1SuppressionsPostRequest) : RequestConfig<V1SuppressionsPostRequest> {
        val localVariableBody = v1SuppressionsPostRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/suppressions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
