/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.CreateCalendarEventRequest

class CreateCalendarEventRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateCalendarEventRequest
        //val modelInstance = CreateCalendarEventRequest()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `startsAt`
        should("test startsAt") {
            // uncomment below to test the property
            //modelInstance.startsAt shouldBe ("TODO")
        }

        // to test the property `endsAt`
        should("test endsAt") {
            // uncomment below to test the property
            //modelInstance.endsAt shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `allDay`
        should("test allDay") {
            // uncomment below to test the property
            //modelInstance.allDay shouldBe ("TODO")
        }

    }
}
