/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.CreateMigrationRequest
import com.lockally.sdk.model.MigrationSettings

class CreateMigrationRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateMigrationRequest
        //val modelInstance = CreateMigrationRequest()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `credentialId`
        should("test credentialId") {
            // uncomment below to test the property
            //modelInstance.credentialId shouldBe ("TODO")
        }

        // to test the property `sourceProvider`
        should("test sourceProvider") {
            // uncomment below to test the property
            //modelInstance.sourceProvider shouldBe ("TODO")
        }

        // to test the property `settings`
        should("test settings") {
            // uncomment below to test the property
            //modelInstance.settings shouldBe ("TODO")
        }

    }
}
