/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.GetAddOnStatus200Response

class GetAddOnStatus200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetAddOnStatus200Response
        //val modelInstance = GetAddOnStatus200Response()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `eligible`
        should("test eligible") {
            // uncomment below to test the property
            //modelInstance.eligible shouldBe ("TODO")
        }

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

    }
}
