/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.GetDomainsStatus200Response
import com.lockally.sdk.model.GetDomainsStatus200ResponseDomainsInner

class GetDomainsStatus200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDomainsStatus200Response
        //val modelInstance = GetDomainsStatus200Response()

        // to test the property `domains`
        should("test domains") {
            // uncomment below to test the property
            //modelInstance.domains shouldBe ("TODO")
        }

        // to test the property `generatedAt`
        should("test generatedAt") {
            // uncomment below to test the property
            //modelInstance.generatedAt shouldBe ("TODO")
        }

    }
}
