/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.GetDirectoryStats200Response

class GetDirectoryStats200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDirectoryStats200Response
        //val modelInstance = GetDirectoryStats200Response()

        // to test the property `totalContacts`
        should("test totalContacts") {
            // uncomment below to test the property
            //modelInstance.totalContacts shouldBe ("TODO")
        }

        // to test the property `internalUsers`
        should("test internalUsers") {
            // uncomment below to test the property
            //modelInstance.internalUsers shouldBe ("TODO")
        }

        // to test the property `externalContacts`
        should("test externalContacts") {
            // uncomment below to test the property
            //modelInstance.externalContacts shouldBe ("TODO")
        }

        // to test the property `syncedContacts`
        should("test syncedContacts") {
            // uncomment below to test the property
            //modelInstance.syncedContacts shouldBe ("TODO")
        }

        // to test the property `sharedLists`
        should("test sharedLists") {
            // uncomment below to test the property
            //modelInstance.sharedLists shouldBe ("TODO")
        }

        // to test the property `directoryGroups`
        should("test directoryGroups") {
            // uncomment below to test the property
            //modelInstance.directoryGroups shouldBe ("TODO")
        }

    }
}
