/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.GetIntegrationsSummary200Response
import com.lockally.sdk.model.GetIntegrationsSummary200ResponseApiKeysInner
import com.lockally.sdk.model.GetIntegrationsSummary200ResponseWebhooksInner

class GetIntegrationsSummary200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetIntegrationsSummary200Response
        //val modelInstance = GetIntegrationsSummary200Response()

        // to test the property `apiRequestsToday`
        should("test apiRequestsToday") {
            // uncomment below to test the property
            //modelInstance.apiRequestsToday shouldBe ("TODO")
        }

        // to test the property `activeApiKeys`
        should("test activeApiKeys") {
            // uncomment below to test the property
            //modelInstance.activeApiKeys shouldBe ("TODO")
        }

        // to test the property `apiKeys`
        should("test apiKeys") {
            // uncomment below to test the property
            //modelInstance.apiKeys shouldBe ("TODO")
        }

        // to test the property `webhookFailures`
        should("test webhookFailures") {
            // uncomment below to test the property
            //modelInstance.webhookFailures shouldBe ("TODO")
        }

        // to test the property `webhooksTotal`
        should("test webhooksTotal") {
            // uncomment below to test the property
            //modelInstance.webhooksTotal shouldBe ("TODO")
        }

        // to test the property `webhooks`
        should("test webhooks") {
            // uncomment below to test the property
            //modelInstance.webhooks shouldBe ("TODO")
        }

        // to test the property `generatedAt`
        should("test generatedAt") {
            // uncomment below to test the property
            //modelInstance.generatedAt shouldBe ("TODO")
        }

    }
}
