/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.GetIntegrationsSummary200ResponseApiKeysInner

class GetIntegrationsSummary200ResponseApiKeysInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetIntegrationsSummary200ResponseApiKeysInner
        //val modelInstance = GetIntegrationsSummary200ResponseApiKeysInner()

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `prefix`
        should("test prefix") {
            // uncomment below to test the property
            //modelInstance.prefix shouldBe ("TODO")
        }

        // to test the property `lastUsedAt`
        should("test lastUsedAt") {
            // uncomment below to test the property
            //modelInstance.lastUsedAt shouldBe ("TODO")
        }

    }
}
