/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.GetIntegrationsSummary200ResponseWebhooksInner

class GetIntegrationsSummary200ResponseWebhooksInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetIntegrationsSummary200ResponseWebhooksInner
        //val modelInstance = GetIntegrationsSummary200ResponseWebhooksInner()

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `paused`
        should("test paused") {
            // uncomment below to test the property
            //modelInstance.paused shouldBe ("TODO")
        }

        // to test the property `consecutiveFailures`
        should("test consecutiveFailures") {
            // uncomment below to test the property
            //modelInstance.consecutiveFailures shouldBe ("TODO")
        }

        // to test the property `lastFailureAt`
        should("test lastFailureAt") {
            // uncomment below to test the property
            //modelInstance.lastFailureAt shouldBe ("TODO")
        }

    }
}
