/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.GetStorage200ResponseTopMessagesInner

class GetStorage200ResponseTopMessagesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStorage200ResponseTopMessagesInner
        //val modelInstance = GetStorage200ResponseTopMessagesInner()

        // to test the property `sender`
        should("test sender") {
            // uncomment below to test the property
            //modelInstance.sender shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `sizeBytes`
        should("test sizeBytes") {
            // uncomment below to test the property
            //modelInstance.sizeBytes shouldBe ("TODO")
        }

        // to test the property `filenames`
        should("test filenames") {
            // uncomment below to test the property
            //modelInstance.filenames shouldBe ("TODO")
        }

        // to test the property `queuedAt`
        should("test queuedAt") {
            // uncomment below to test the property
            //modelInstance.queuedAt shouldBe ("TODO")
        }

    }
}
