/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.GetStorage200ResponseTopMailboxesInner

class GetStorage200ResponseTopMailboxesInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStorage200ResponseTopMailboxesInner
        //val modelInstance = GetStorage200ResponseTopMailboxesInner()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `usageBytes`
        should("test usageBytes") {
            // uncomment below to test the property
            //modelInstance.usageBytes shouldBe ("TODO")
        }

    }
}
