/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.Mailbox

class MailboxTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Mailbox
        //val modelInstance = Mailbox()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `domainId`
        should("test domainId") {
            // uncomment below to test the property
            //modelInstance.domainId shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `quotaBytes`
        should("test quotaBytes") {
            // uncomment below to test the property
            //modelInstance.quotaBytes shouldBe ("TODO")
        }

        // to test the property `disabled`
        should("test disabled") {
            // uncomment below to test the property
            //modelInstance.disabled shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `disabledAt`
        should("test disabledAt") {
            // uncomment below to test the property
            //modelInstance.disabledAt shouldBe ("TODO")
        }

        // to test the property `softDeletedAt`
        should("test softDeletedAt") {
            // uncomment below to test the property
            //modelInstance.softDeletedAt shouldBe ("TODO")
        }

        // to test the property `hardDeleteAfter`
        should("test hardDeleteAfter") {
            // uncomment below to test the property
            //modelInstance.hardDeleteAfter shouldBe ("TODO")
        }

        // to test the property `password` - ONLY present on POST response when lockally generated the password. Shown once.
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

    }
}
