/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.MapMigrationRequestMappingsInner

class MapMigrationRequestMappingsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MapMigrationRequestMappingsInner
        //val modelInstance = MapMigrationRequestMappingsInner()

        // to test the property `sourceEmail`
        should("test sourceEmail") {
            // uncomment below to test the property
            //modelInstance.sourceEmail shouldBe ("TODO")
        }

        // to test the property `destEmail`
        should("test destEmail") {
            // uncomment below to test the property
            //modelInstance.destEmail shouldBe ("TODO")
        }

    }
}
