/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.SignupRequest

class SignupRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SignupRequest
        //val modelInstance = SignupRequest()

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `adminEmail`
        should("test adminEmail") {
            // uncomment below to test the property
            //modelInstance.adminEmail shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `mode`
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

    }
}
