/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.UnitBundle

class UnitBundleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UnitBundle
        //val modelInstance = UnitBundle()

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `units`
        should("test units") {
            // uncomment below to test the property
            //modelInstance.units shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `priceNaira`
        should("test priceNaira") {
            // uncomment below to test the property
            //modelInstance.priceNaira shouldBe ("TODO")
        }

        // to test the property `displayPrice`
        should("test displayPrice") {
            // uncomment below to test the property
            //modelInstance.displayPrice shouldBe ("TODO")
        }

    }
}
