/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.UserEvent

class UserEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserEvent
        //val modelInstance = UserEvent()

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `eventAt`
        should("test eventAt") {
            // uncomment below to test the property
            //modelInstance.eventAt shouldBe ("TODO")
        }

        // to test the property `daysInactive`
        should("test daysInactive") {
            // uncomment below to test the property
            //modelInstance.daysInactive shouldBe ("TODO")
        }

    }
}
