/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.V1AliasesPostRequest

class V1AliasesPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of V1AliasesPostRequest
        //val modelInstance = V1AliasesPostRequest()

        // to test the property `aliasAddress`
        should("test aliasAddress") {
            // uncomment below to test the property
            //modelInstance.aliasAddress shouldBe ("TODO")
        }

        // to test the property `aliasTarget`
        should("test aliasTarget") {
            // uncomment below to test the property
            //modelInstance.aliasTarget shouldBe ("TODO")
        }

    }
}
