/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.V1ApiKeysPost201Response

class V1ApiKeysPost201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of V1ApiKeysPost201Response
        //val modelInstance = V1ApiKeysPost201Response()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `prefix` - 8-char public prefix; safe to store and display.
        should("test prefix") {
            // uncomment below to test the property
            //modelInstance.prefix shouldBe ("TODO")
        }

        // to test the property `scopes`
        should("test scopes") {
            // uncomment below to test the property
            //modelInstance.scopes shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `secret` - The full `lk_live_<prefix>_<secret>` token. Shown ONCE.
        should("test secret") {
            // uncomment below to test the property
            //modelInstance.secret shouldBe ("TODO")
        }

        // to test the property `lastUsedAt`
        should("test lastUsedAt") {
            // uncomment below to test the property
            //modelInstance.lastUsedAt shouldBe ("TODO")
        }

        // to test the property `revokedAt`
        should("test revokedAt") {
            // uncomment below to test the property
            //modelInstance.revokedAt shouldBe ("TODO")
        }

    }
}
