/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.V1ApiKeysPostRequest

class V1ApiKeysPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of V1ApiKeysPostRequest
        //val modelInstance = V1ApiKeysPostRequest()

        // to test the property `label` - Free-text identifier shown in the dashboard.
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `scopes` - Allowed scopes on this key.
        should("test scopes") {
            // uncomment below to test the property
            //modelInstance.scopes shouldBe ("TODO")
        }

    }
}
