/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.model.Webhook

class WebhookTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Webhook
        //val modelInstance = Webhook()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `events`
        should("test events") {
            // uncomment below to test the property
            //modelInstance.events shouldBe ("TODO")
        }

        // to test the property `paused`
        should("test paused") {
            // uncomment below to test the property
            //modelInstance.paused shouldBe ("TODO")
        }

        // to test the property `consecutiveFailures`
        should("test consecutiveFailures") {
            // uncomment below to test the property
            //modelInstance.consecutiveFailures shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `pausedAt`
        should("test pausedAt") {
            // uncomment below to test the property
            //modelInstance.pausedAt shouldBe ("TODO")
        }

        // to test the property `lastSuccessAt`
        should("test lastSuccessAt") {
            // uncomment below to test the property
            //modelInstance.lastSuccessAt shouldBe ("TODO")
        }

        // to test the property `lastFailureAt`
        should("test lastFailureAt") {
            // uncomment below to test the property
            //modelInstance.lastFailureAt shouldBe ("TODO")
        }

        // to test the property `signingSecret` - Hex-encoded HMAC-SHA256 key. Present ONLY on POST response.
        should("test signingSecret") {
            // uncomment below to test the property
            //modelInstance.signingSecret shouldBe ("TODO")
        }

    }
}
