/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.AddOnsApi
import com.lockally.sdk.model.ActivateAddOn200Response
import com.lockally.sdk.model.GetAddOnStatus200Response
import com.lockally.sdk.model.ListAddOns200Response
import com.lockally.sdk.model.Problem

class AddOnsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddOnsApi
        //val apiInstance = AddOnsApi()

        // to test activateAddOn
        should("test activateAddOn") {
            // uncomment below to test activateAddOn
            //val name : kotlin.String = name_example // kotlin.String | Add-on key
            //val result : ActivateAddOn200Response = apiInstance.activateAddOn(name)
            //result shouldBe ("TODO")
        }

        // to test cancelAddOn
        should("test cancelAddOn") {
            // uncomment below to test cancelAddOn
            //val name : kotlin.String = name_example // kotlin.String | Add-on key
            //apiInstance.cancelAddOn(name)
        }

        // to test getAddOnStatus
        should("test getAddOnStatus") {
            // uncomment below to test getAddOnStatus
            //val name : kotlin.String = name_example // kotlin.String | Add-on key
            //val result : GetAddOnStatus200Response = apiInstance.getAddOnStatus(name)
            //result shouldBe ("TODO")
        }

        // to test listAddOns
        should("test listAddOns") {
            // uncomment below to test listAddOns
            //val result : ListAddOns200Response = apiInstance.listAddOns()
            //result shouldBe ("TODO")
        }

    }
}
