/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.AiApi

class AiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AiApi
        //val apiInstance = AiApi()

        // to test v1AiConfigGet
        should("test v1AiConfigGet") {
            // uncomment below to test v1AiConfigGet
            //val result : kotlin.Any = apiInstance.v1AiConfigGet()
            //result shouldBe ("TODO")
        }

        // to test v1AiConfigPut
        should("test v1AiConfigPut") {
            // uncomment below to test v1AiConfigPut
            //val result : kotlin.Any = apiInstance.v1AiConfigPut()
            //result shouldBe ("TODO")
        }

        // to test v1BillingAiUnitsCheckoutPost
        should("test v1BillingAiUnitsCheckoutPost") {
            // uncomment below to test v1BillingAiUnitsCheckoutPost
            //val result : kotlin.Any = apiInstance.v1BillingAiUnitsCheckoutPost()
            //result shouldBe ("TODO")
        }

        // to test v1ThreadsThreadIDClassifyPost
        should("test v1ThreadsThreadIDClassifyPost") {
            // uncomment below to test v1ThreadsThreadIDClassifyPost
            //val threadID : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val refresh : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.Any = apiInstance.v1ThreadsThreadIDClassifyPost(threadID, refresh)
            //result shouldBe ("TODO")
        }

    }
}
