/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.AliasesApi
import com.lockally.sdk.model.Alias
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.V1AliasesGet200Response
import com.lockally.sdk.model.V1AliasesPostRequest

class AliasesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AliasesApi
        //val apiInstance = AliasesApi()

        // to test v1AliasesAddressDelete
        should("test v1AliasesAddressDelete") {
            // uncomment below to test v1AliasesAddressDelete
            //val address : kotlin.String = address_example // kotlin.String | 
            //apiInstance.v1AliasesAddressDelete(address)
        }

        // to test v1AliasesGet
        should("test v1AliasesGet") {
            // uncomment below to test v1AliasesGet
            //val result : V1AliasesGet200Response = apiInstance.v1AliasesGet()
            //result shouldBe ("TODO")
        }

        // to test v1AliasesPost
        should("test v1AliasesPost") {
            // uncomment below to test v1AliasesPost
            //val v1AliasesPostRequest : V1AliasesPostRequest =  // V1AliasesPostRequest | 
            //val result : Alias = apiInstance.v1AliasesPost(v1AliasesPostRequest)
            //result shouldBe ("TODO")
        }

    }
}
