/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.ApiKeysApi
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.V1ApiKeysGet200Response
import com.lockally.sdk.model.V1ApiKeysPost201Response
import com.lockally.sdk.model.V1ApiKeysPostRequest

class ApiKeysApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiKeysApi
        //val apiInstance = ApiKeysApi()

        // to test v1ApiKeysGet
        should("test v1ApiKeysGet") {
            // uncomment below to test v1ApiKeysGet
            //val result : V1ApiKeysGet200Response = apiInstance.v1ApiKeysGet()
            //result shouldBe ("TODO")
        }

        // to test v1ApiKeysIdDelete
        should("test v1ApiKeysIdDelete") {
            // uncomment below to test v1ApiKeysIdDelete
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.v1ApiKeysIdDelete(id)
        }

        // to test v1ApiKeysPost
        should("test v1ApiKeysPost") {
            // uncomment below to test v1ApiKeysPost
            //val v1ApiKeysPostRequest : V1ApiKeysPostRequest =  // V1ApiKeysPostRequest | 
            //val result : V1ApiKeysPost201Response = apiInstance.v1ApiKeysPost(v1ApiKeysPostRequest)
            //result shouldBe ("TODO")
        }

    }
}
