/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.BillingApi
import com.lockally.sdk.model.BillingStatus
import com.lockally.sdk.model.CreateBillingCheckout200Response
import com.lockally.sdk.model.CreateBillingCheckoutRequest
import com.lockally.sdk.model.CreateUnitsCheckout200Response
import com.lockally.sdk.model.CreateUnitsCheckoutRequest
import com.lockally.sdk.model.Problem

class BillingApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BillingApi
        //val apiInstance = BillingApi()

        // to test createBillingCheckout
        should("test createBillingCheckout") {
            // uncomment below to test createBillingCheckout
            //val createBillingCheckoutRequest : CreateBillingCheckoutRequest =  // CreateBillingCheckoutRequest | 
            //val result : CreateBillingCheckout200Response = apiInstance.createBillingCheckout(createBillingCheckoutRequest)
            //result shouldBe ("TODO")
        }

        // to test createUnitsCheckout
        should("test createUnitsCheckout") {
            // uncomment below to test createUnitsCheckout
            //val createUnitsCheckoutRequest : CreateUnitsCheckoutRequest =  // CreateUnitsCheckoutRequest | 
            //val result : CreateUnitsCheckout200Response = apiInstance.createUnitsCheckout(createUnitsCheckoutRequest)
            //result shouldBe ("TODO")
        }

        // to test getBilling
        should("test getBilling") {
            // uncomment below to test getBilling
            //val result : BillingStatus = apiInstance.getBilling()
            //result shouldBe ("TODO")
        }

    }
}
