/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.CalendarsApi
import com.lockally.sdk.model.AddCalendarMemberRequest
import com.lockally.sdk.model.Calendar
import com.lockally.sdk.model.CalendarEvent
import com.lockally.sdk.model.CalendarIntegration
import com.lockally.sdk.model.CalendarMember
import com.lockally.sdk.model.CalendarPolicies
import com.lockally.sdk.model.CreateCalendarEventRequest
import com.lockally.sdk.model.CreateCalendarIntegrationRequest
import com.lockally.sdk.model.CreateCalendarRequest
import com.lockally.sdk.model.GetCalendarSecurity200Response
import com.lockally.sdk.model.ListCalendarEvents200Response
import com.lockally.sdk.model.ListCalendarIntegrations200Response
import com.lockally.sdk.model.ListCalendarMembers200Response
import com.lockally.sdk.model.ListCalendars200Response
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.UpdateCalendarEventRequest
import com.lockally.sdk.model.UpdateCalendarIntegrationRequest
import com.lockally.sdk.model.UpdateCalendarMemberRequest
import com.lockally.sdk.model.UpdateCalendarPoliciesRequest
import com.lockally.sdk.model.UpdateCalendarRequest

class CalendarsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CalendarsApi
        //val apiInstance = CalendarsApi()

        // to test addCalendarMember
        should("test addCalendarMember") {
            // uncomment below to test addCalendarMember
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val addCalendarMemberRequest : AddCalendarMemberRequest =  // AddCalendarMemberRequest | 
            //val result : CalendarMember = apiInstance.addCalendarMember(id, addCalendarMemberRequest)
            //result shouldBe ("TODO")
        }

        // to test createCalendar
        should("test createCalendar") {
            // uncomment below to test createCalendar
            //val createCalendarRequest : CreateCalendarRequest =  // CreateCalendarRequest | 
            //val result : Calendar = apiInstance.createCalendar(createCalendarRequest)
            //result shouldBe ("TODO")
        }

        // to test createCalendarEvent
        should("test createCalendarEvent") {
            // uncomment below to test createCalendarEvent
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val createCalendarEventRequest : CreateCalendarEventRequest =  // CreateCalendarEventRequest | 
            //val result : CalendarEvent = apiInstance.createCalendarEvent(id, createCalendarEventRequest)
            //result shouldBe ("TODO")
        }

        // to test createCalendarIntegration
        should("test createCalendarIntegration") {
            // uncomment below to test createCalendarIntegration
            //val createCalendarIntegrationRequest : CreateCalendarIntegrationRequest =  // CreateCalendarIntegrationRequest | 
            //val result : CalendarIntegration = apiInstance.createCalendarIntegration(createCalendarIntegrationRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteCalendar
        should("test deleteCalendar") {
            // uncomment below to test deleteCalendar
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteCalendar(id)
        }

        // to test deleteCalendarEvent
        should("test deleteCalendarEvent") {
            // uncomment below to test deleteCalendarEvent
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val eventId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteCalendarEvent(id, eventId)
        }

        // to test deleteCalendarIntegration
        should("test deleteCalendarIntegration") {
            // uncomment below to test deleteCalendarIntegration
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteCalendarIntegration(id)
        }

        // to test getCalendar
        should("test getCalendar") {
            // uncomment below to test getCalendar
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : Calendar = apiInstance.getCalendar(id)
            //result shouldBe ("TODO")
        }

        // to test getCalendarPolicies
        should("test getCalendarPolicies") {
            // uncomment below to test getCalendarPolicies
            //val result : CalendarPolicies = apiInstance.getCalendarPolicies()
            //result shouldBe ("TODO")
        }

        // to test getCalendarSecurity
        should("test getCalendarSecurity") {
            // uncomment below to test getCalendarSecurity
            //val result : GetCalendarSecurity200Response = apiInstance.getCalendarSecurity()
            //result shouldBe ("TODO")
        }

        // to test listCalendarEvents
        should("test listCalendarEvents") {
            // uncomment below to test listCalendarEvents
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val from : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | 
            //val to : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | 
            //val result : ListCalendarEvents200Response = apiInstance.listCalendarEvents(id, from, to)
            //result shouldBe ("TODO")
        }

        // to test listCalendarIntegrations
        should("test listCalendarIntegrations") {
            // uncomment below to test listCalendarIntegrations
            //val result : ListCalendarIntegrations200Response = apiInstance.listCalendarIntegrations()
            //result shouldBe ("TODO")
        }

        // to test listCalendarMembers
        should("test listCalendarMembers") {
            // uncomment below to test listCalendarMembers
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : ListCalendarMembers200Response = apiInstance.listCalendarMembers(id)
            //result shouldBe ("TODO")
        }

        // to test listCalendars
        should("test listCalendars") {
            // uncomment below to test listCalendars
            //val result : ListCalendars200Response = apiInstance.listCalendars()
            //result shouldBe ("TODO")
        }

        // to test removeCalendarMember
        should("test removeCalendarMember") {
            // uncomment below to test removeCalendarMember
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val memberId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.removeCalendarMember(id, memberId)
        }

        // to test syncCalendarIntegration
        should("test syncCalendarIntegration") {
            // uncomment below to test syncCalendarIntegration
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : CalendarIntegration = apiInstance.syncCalendarIntegration(id)
            //result shouldBe ("TODO")
        }

        // to test updateCalendar
        should("test updateCalendar") {
            // uncomment below to test updateCalendar
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateCalendarRequest : UpdateCalendarRequest =  // UpdateCalendarRequest | 
            //val result : Calendar = apiInstance.updateCalendar(id, updateCalendarRequest)
            //result shouldBe ("TODO")
        }

        // to test updateCalendarEvent
        should("test updateCalendarEvent") {
            // uncomment below to test updateCalendarEvent
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val eventId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateCalendarEventRequest : UpdateCalendarEventRequest =  // UpdateCalendarEventRequest | 
            //val result : CalendarEvent = apiInstance.updateCalendarEvent(id, eventId, updateCalendarEventRequest)
            //result shouldBe ("TODO")
        }

        // to test updateCalendarIntegration
        should("test updateCalendarIntegration") {
            // uncomment below to test updateCalendarIntegration
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateCalendarIntegrationRequest : UpdateCalendarIntegrationRequest =  // UpdateCalendarIntegrationRequest | 
            //val result : CalendarIntegration = apiInstance.updateCalendarIntegration(id, updateCalendarIntegrationRequest)
            //result shouldBe ("TODO")
        }

        // to test updateCalendarMember
        should("test updateCalendarMember") {
            // uncomment below to test updateCalendarMember
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val memberId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateCalendarMemberRequest : UpdateCalendarMemberRequest =  // UpdateCalendarMemberRequest | 
            //val result : CalendarMember = apiInstance.updateCalendarMember(id, memberId, updateCalendarMemberRequest)
            //result shouldBe ("TODO")
        }

        // to test updateCalendarPolicies
        should("test updateCalendarPolicies") {
            // uncomment below to test updateCalendarPolicies
            //val updateCalendarPoliciesRequest : UpdateCalendarPoliciesRequest =  // UpdateCalendarPoliciesRequest | 
            //val result : CalendarPolicies = apiInstance.updateCalendarPolicies(updateCalendarPoliciesRequest)
            //result shouldBe ("TODO")
        }

    }
}
