/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.DashboardApi
import com.lockally.sdk.model.GetAuditSummary200Response
import com.lockally.sdk.model.GetDomainsStatus200Response
import com.lockally.sdk.model.GetIntegrationsSummary200Response
import com.lockally.sdk.model.GetSecurity200Response
import com.lockally.sdk.model.GetStorage200Response
import com.lockally.sdk.model.GetUserInsights200Response
import com.lockally.sdk.model.Problem

class DashboardApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DashboardApi
        //val apiInstance = DashboardApi()

        // to test getAuditSummary
        should("test getAuditSummary") {
            // uncomment below to test getAuditSummary
            //val result : GetAuditSummary200Response = apiInstance.getAuditSummary()
            //result shouldBe ("TODO")
        }

        // to test getDomainsStatus
        should("test getDomainsStatus") {
            // uncomment below to test getDomainsStatus
            //val result : GetDomainsStatus200Response = apiInstance.getDomainsStatus()
            //result shouldBe ("TODO")
        }

        // to test getIntegrationsSummary
        should("test getIntegrationsSummary") {
            // uncomment below to test getIntegrationsSummary
            //val result : GetIntegrationsSummary200Response = apiInstance.getIntegrationsSummary()
            //result shouldBe ("TODO")
        }

        // to test getSecurity
        should("test getSecurity") {
            // uncomment below to test getSecurity
            //val result : GetSecurity200Response = apiInstance.getSecurity()
            //result shouldBe ("TODO")
        }

        // to test getStorage
        should("test getStorage") {
            // uncomment below to test getStorage
            //val result : GetStorage200Response = apiInstance.getStorage()
            //result shouldBe ("TODO")
        }

        // to test getTenantHealth
        should("test getTenantHealth") {
            // uncomment below to test getTenantHealth
            //val result : kotlin.Any = apiInstance.getTenantHealth()
            //result shouldBe ("TODO")
        }

        // to test getUserInsights
        should("test getUserInsights") {
            // uncomment below to test getUserInsights
            //val result : GetUserInsights200Response = apiInstance.getUserInsights()
            //result shouldBe ("TODO")
        }

    }
}
