/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.DirectoryApi
import com.lockally.sdk.model.DirectoryPermissions
import com.lockally.sdk.model.GALSettings
import com.lockally.sdk.model.GetDirectoryActivity200Response
import com.lockally.sdk.model.GetDirectoryStats200Response
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.UpdateDirectoryPermissionsRequest
import com.lockally.sdk.model.UpdateGALSettingsRequest

class DirectoryApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DirectoryApi
        //val apiInstance = DirectoryApi()

        // to test getDirectoryActivity
        should("test getDirectoryActivity") {
            // uncomment below to test getDirectoryActivity
            //val result : GetDirectoryActivity200Response = apiInstance.getDirectoryActivity()
            //result shouldBe ("TODO")
        }

        // to test getDirectoryPermissions
        should("test getDirectoryPermissions") {
            // uncomment below to test getDirectoryPermissions
            //val result : DirectoryPermissions = apiInstance.getDirectoryPermissions()
            //result shouldBe ("TODO")
        }

        // to test getDirectoryStats
        should("test getDirectoryStats") {
            // uncomment below to test getDirectoryStats
            //val result : GetDirectoryStats200Response = apiInstance.getDirectoryStats()
            //result shouldBe ("TODO")
        }

        // to test getGALSettings
        should("test getGALSettings") {
            // uncomment below to test getGALSettings
            //val result : GALSettings = apiInstance.getGALSettings()
            //result shouldBe ("TODO")
        }

        // to test rebuildGALIndex
        should("test rebuildGALIndex") {
            // uncomment below to test rebuildGALIndex
            //val result : GALSettings = apiInstance.rebuildGALIndex()
            //result shouldBe ("TODO")
        }

        // to test syncGAL
        should("test syncGAL") {
            // uncomment below to test syncGAL
            //val result : GALSettings = apiInstance.syncGAL()
            //result shouldBe ("TODO")
        }

        // to test updateDirectoryPermissions
        should("test updateDirectoryPermissions") {
            // uncomment below to test updateDirectoryPermissions
            //val updateDirectoryPermissionsRequest : UpdateDirectoryPermissionsRequest =  // UpdateDirectoryPermissionsRequest | 
            //val result : DirectoryPermissions = apiInstance.updateDirectoryPermissions(updateDirectoryPermissionsRequest)
            //result shouldBe ("TODO")
        }

        // to test updateGALSettings
        should("test updateGALSettings") {
            // uncomment below to test updateGALSettings
            //val updateGALSettingsRequest : UpdateGALSettingsRequest =  // UpdateGALSettingsRequest | 
            //val result : GALSettings = apiInstance.updateGALSettings(updateGALSettingsRequest)
            //result shouldBe ("TODO")
        }

    }
}
