/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.DistributionListsApi
import com.lockally.sdk.model.CreateDistributionListRequest
import com.lockally.sdk.model.DistributionListDetail
import com.lockally.sdk.model.ListDistributionLists200Response
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.ReplaceDistributionListMembers200Response
import com.lockally.sdk.model.ReplaceDistributionListMembersRequest

class DistributionListsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DistributionListsApi
        //val apiInstance = DistributionListsApi()

        // to test createDistributionList
        should("test createDistributionList") {
            // uncomment below to test createDistributionList
            //val createDistributionListRequest : CreateDistributionListRequest =  // CreateDistributionListRequest | 
            //val result : DistributionListDetail = apiInstance.createDistributionList(createDistributionListRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteDistributionList
        should("test deleteDistributionList") {
            // uncomment below to test deleteDistributionList
            //val address : kotlin.String = address_example // kotlin.String | Distribution list email address
            //apiInstance.deleteDistributionList(address)
        }

        // to test getDistributionList
        should("test getDistributionList") {
            // uncomment below to test getDistributionList
            //val address : kotlin.String = address_example // kotlin.String | Distribution list email address
            //val result : DistributionListDetail = apiInstance.getDistributionList(address)
            //result shouldBe ("TODO")
        }

        // to test listDistributionLists
        should("test listDistributionLists") {
            // uncomment below to test listDistributionLists
            //val result : ListDistributionLists200Response = apiInstance.listDistributionLists()
            //result shouldBe ("TODO")
        }

        // to test replaceDistributionListMembers
        should("test replaceDistributionListMembers") {
            // uncomment below to test replaceDistributionListMembers
            //val address : kotlin.String = address_example // kotlin.String | Distribution list email address
            //val replaceDistributionListMembersRequest : ReplaceDistributionListMembersRequest =  // ReplaceDistributionListMembersRequest | 
            //val result : ReplaceDistributionListMembers200Response = apiInstance.replaceDistributionListMembers(address, replaceDistributionListMembersRequest)
            //result shouldBe ("TODO")
        }

    }
}
