/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.HealthApi
import com.lockally.sdk.model.HealthzGet200Response
import com.lockally.sdk.model.Problem

class HealthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthApi
        //val apiInstance = HealthApi()

        // to test healthzGet
        should("test healthzGet") {
            // uncomment below to test healthzGet
            //val result : HealthzGet200Response = apiInstance.healthzGet()
            //result shouldBe ("TODO")
        }

    }
}
