/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.ResourcesApi
import com.lockally.sdk.model.CreateResourceRequest
import com.lockally.sdk.model.ListResources200Response
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.Resource
import com.lockally.sdk.model.UpdateResourceRequest

class ResourcesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourcesApi
        //val apiInstance = ResourcesApi()

        // to test createResource
        should("test createResource") {
            // uncomment below to test createResource
            //val createResourceRequest : CreateResourceRequest =  // CreateResourceRequest | 
            //val result : Resource = apiInstance.createResource(createResourceRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteResource
        should("test deleteResource") {
            // uncomment below to test deleteResource
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteResource(id)
        }

        // to test getResource
        should("test getResource") {
            // uncomment below to test getResource
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : Resource = apiInstance.getResource(id)
            //result shouldBe ("TODO")
        }

        // to test listResources
        should("test listResources") {
            // uncomment below to test listResources
            //val result : ListResources200Response = apiInstance.listResources()
            //result shouldBe ("TODO")
        }

        // to test updateResource
        should("test updateResource") {
            // uncomment below to test updateResource
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateResourceRequest : UpdateResourceRequest =  // UpdateResourceRequest | 
            //val result : Resource = apiInstance.updateResource(id, updateResourceRequest)
            //result shouldBe ("TODO")
        }

    }
}
