/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.SendApi
import com.lockally.sdk.model.MessageDetail
import com.lockally.sdk.model.MessageStats
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.V1MessagesGet200Response
import com.lockally.sdk.model.V1SendBatchPost200Response
import com.lockally.sdk.model.V1SendBatchPostRequest
import com.lockally.sdk.model.V1SendPost202Response
import com.lockally.sdk.model.V1SendPostRequest

class SendApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SendApi
        //val apiInstance = SendApi()

        // to test v1MessagesGet
        should("test v1MessagesGet") {
            // uncomment below to test v1MessagesGet
            //val status : kotlin.String = status_example // kotlin.String | 
            //val sender : kotlin.String = sender_example // kotlin.String | Exact match against the `from` mailbox.
            //val q : kotlin.String = q_example // kotlin.String | Free-text search across subject + sender.
            //val since : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Only messages queued at or after this RFC 3339 instant.
            //val cursor : kotlin.String = cursor_example // kotlin.String | queued_at of the prior page boundary. Pass back the `next_cursor` returned by the previous call.
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : V1MessagesGet200Response = apiInstance.v1MessagesGet(status, sender, q, since, cursor, limit)
            //result shouldBe ("TODO")
        }

        // to test v1MessagesIdDelete
        should("test v1MessagesIdDelete") {
            // uncomment below to test v1MessagesIdDelete
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.v1MessagesIdDelete(id)
        }

        // to test v1MessagesIdGet
        should("test v1MessagesIdGet") {
            // uncomment below to test v1MessagesIdGet
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : MessageDetail = apiInstance.v1MessagesIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test v1MessagesStatsGet
        should("test v1MessagesStatsGet") {
            // uncomment below to test v1MessagesStatsGet
            //val from : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Window start (default 7 days ago).
            //val to : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Window end (default now).
            //val domain : kotlin.String = domain_example // kotlin.String | Filter by sender domain.
            //val result : MessageStats = apiInstance.v1MessagesStatsGet(from, to, domain)
            //result shouldBe ("TODO")
        }

        // to test v1SendBatchPost
        should("test v1SendBatchPost") {
            // uncomment below to test v1SendBatchPost
            //val idempotencyKey : kotlin.String = idempotencyKey_example // kotlin.String | 
            //val v1SendBatchPostRequest : V1SendBatchPostRequest =  // V1SendBatchPostRequest | 
            //val result : V1SendBatchPost200Response = apiInstance.v1SendBatchPost(idempotencyKey, v1SendBatchPostRequest)
            //result shouldBe ("TODO")
        }

        // to test v1SendPost
        should("test v1SendPost") {
            // uncomment below to test v1SendPost
            //val idempotencyKey : kotlin.String = idempotencyKey_example // kotlin.String | 
            //val v1SendPostRequest : V1SendPostRequest =  // V1SendPostRequest | 
            //val result : V1SendPost202Response = apiInstance.v1SendPost(idempotencyKey, v1SendPostRequest)
            //result shouldBe ("TODO")
        }

    }
}
