/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.SuppressionsApi
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.Suppression
import com.lockally.sdk.model.V1SuppressionsGet200Response
import com.lockally.sdk.model.V1SuppressionsPostRequest

class SuppressionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuppressionsApi
        //val apiInstance = SuppressionsApi()

        // to test v1SuppressionsEmailDelete
        should("test v1SuppressionsEmailDelete") {
            // uncomment below to test v1SuppressionsEmailDelete
            //val email : kotlin.String = email_example // kotlin.String | 
            //apiInstance.v1SuppressionsEmailDelete(email)
        }

        // to test v1SuppressionsEmailGet
        should("test v1SuppressionsEmailGet") {
            // uncomment below to test v1SuppressionsEmailGet
            //val email : kotlin.String = email_example // kotlin.String | 
            //val result : Suppression = apiInstance.v1SuppressionsEmailGet(email)
            //result shouldBe ("TODO")
        }

        // to test v1SuppressionsGet
        should("test v1SuppressionsGet") {
            // uncomment below to test v1SuppressionsGet
            //val reason : kotlin.String = reason_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : V1SuppressionsGet200Response = apiInstance.v1SuppressionsGet(reason, cursor, limit)
            //result shouldBe ("TODO")
        }

        // to test v1SuppressionsPost
        should("test v1SuppressionsPost") {
            // uncomment below to test v1SuppressionsPost
            //val v1SuppressionsPostRequest : V1SuppressionsPostRequest =  // V1SuppressionsPostRequest | 
            //val result : Suppression = apiInstance.v1SuppressionsPost(v1SuppressionsPostRequest)
            //result shouldBe ("TODO")
        }

    }
}
