/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.TestApi

class TestApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestApi
        //val apiInstance = TestApi()

        // to test v1TestInboundPost
        should("test v1TestInboundPost") {
            // uncomment below to test v1TestInboundPost
            //val result : kotlin.Any = apiInstance.v1TestInboundPost()
            //result shouldBe ("TODO")
        }

    }
}
