/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.lockally.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.lockally.sdk.api.UsersApi
import com.lockally.sdk.model.CreateUserRequest
import com.lockally.sdk.model.ListUsers200Response
import com.lockally.sdk.model.Problem
import com.lockally.sdk.model.UpdateUserRequest
import com.lockally.sdk.model.User

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test createUser
        should("test createUser") {
            // uncomment below to test createUser
            //val createUserRequest : CreateUserRequest =  // CreateUserRequest | 
            //val result : User = apiInstance.createUser(createUserRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteUser
        should("test deleteUser") {
            // uncomment below to test deleteUser
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.deleteUser(id)
        }

        // to test getUser
        should("test getUser") {
            // uncomment below to test getUser
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : User = apiInstance.getUser(id)
            //result shouldBe ("TODO")
        }

        // to test listUsers
        should("test listUsers") {
            // uncomment below to test listUsers
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : ListUsers200Response = apiInstance.listUsers(limit)
            //result shouldBe ("TODO")
        }

        // to test updateUser
        should("test updateUser") {
            // uncomment below to test updateUser
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val updateUserRequest : UpdateUserRequest =  // UpdateUserRequest | 
            //val result : User = apiInstance.updateUser(id, updateUserRequest)
            //result shouldBe ("TODO")
        }

    }
}
